// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: contracts/proto/order_execution.proto

package orderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderExecutionService_SubmitOrder_FullMethodName  = "/reef.contracts.orderexecution.v1.OrderExecutionService/SubmitOrder"
	OrderExecutionService_SubmitOrders_FullMethodName = "/reef.contracts.orderexecution.v1.OrderExecutionService/SubmitOrders"
	OrderExecutionService_CancelOrder_FullMethodName  = "/reef.contracts.orderexecution.v1.OrderExecutionService/CancelOrder"
	OrderExecutionService_ModifyOrder_FullMethodName  = "/reef.contracts.orderexecution.v1.OrderExecutionService/ModifyOrder"
	OrderExecutionService_HealthCheck_FullMethodName  = "/reef.contracts.orderexecution.v1.OrderExecutionService/HealthCheck"
)

// OrderExecutionServiceClient is the client API for OrderExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderExecutionServiceClient interface {
	SubmitOrder(ctx context.Context, in *SubmitOrder, opts ...grpc.CallOption) (*SubmitOrderResult, error)
	SubmitOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubmitOrder, SubmitOrderResult], error)
	CancelOrder(ctx context.Context, in *CancelOrder, opts ...grpc.CallOption) (*SubmitOrderResult, error)
	ModifyOrder(ctx context.Context, in *ModifyOrder, opts ...grpc.CallOption) (*SubmitOrderResult, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type orderExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderExecutionServiceClient(cc grpc.ClientConnInterface) OrderExecutionServiceClient {
	return &orderExecutionServiceClient{cc}
}

func (c *orderExecutionServiceClient) SubmitOrder(ctx context.Context, in *SubmitOrder, opts ...grpc.CallOption) (*SubmitOrderResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitOrderResult)
	err := c.cc.Invoke(ctx, OrderExecutionService_SubmitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderExecutionServiceClient) SubmitOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubmitOrder, SubmitOrderResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderExecutionService_ServiceDesc.Streams[0], OrderExecutionService_SubmitOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubmitOrder, SubmitOrderResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderExecutionService_SubmitOrdersClient = grpc.BidiStreamingClient[SubmitOrder, SubmitOrderResult]

func (c *orderExecutionServiceClient) CancelOrder(ctx context.Context, in *CancelOrder, opts ...grpc.CallOption) (*SubmitOrderResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitOrderResult)
	err := c.cc.Invoke(ctx, OrderExecutionService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderExecutionServiceClient) ModifyOrder(ctx context.Context, in *ModifyOrder, opts ...grpc.CallOption) (*SubmitOrderResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitOrderResult)
	err := c.cc.Invoke(ctx, OrderExecutionService_ModifyOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderExecutionServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, OrderExecutionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderExecutionServiceServer is the server API for OrderExecutionService service.
// All implementations must embed UnimplementedOrderExecutionServiceServer
// for forward compatibility.
type OrderExecutionServiceServer interface {
	SubmitOrder(context.Context, *SubmitOrder) (*SubmitOrderResult, error)
	SubmitOrders(grpc.BidiStreamingServer[SubmitOrder, SubmitOrderResult]) error
	CancelOrder(context.Context, *CancelOrder) (*SubmitOrderResult, error)
	ModifyOrder(context.Context, *ModifyOrder) (*SubmitOrderResult, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedOrderExecutionServiceServer()
}

// UnimplementedOrderExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderExecutionServiceServer struct{}

func (UnimplementedOrderExecutionServiceServer) SubmitOrder(context.Context, *SubmitOrder) (*SubmitOrderResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (UnimplementedOrderExecutionServiceServer) SubmitOrders(grpc.BidiStreamingServer[SubmitOrder, SubmitOrderResult]) error {
	return status.Errorf(codes.Unimplemented, "method SubmitOrders not implemented")
}
func (UnimplementedOrderExecutionServiceServer) CancelOrder(context.Context, *CancelOrder) (*SubmitOrderResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderExecutionServiceServer) ModifyOrder(context.Context, *ModifyOrder) (*SubmitOrderResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyOrder not implemented")
}
func (UnimplementedOrderExecutionServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedOrderExecutionServiceServer) mustEmbedUnimplementedOrderExecutionServiceServer() {}
func (UnimplementedOrderExecutionServiceServer) testEmbeddedByValue()                               {}

// UnsafeOrderExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderExecutionServiceServer will
// result in compilation errors.
type UnsafeOrderExecutionServiceServer interface {
	mustEmbedUnimplementedOrderExecutionServiceServer()
}

func RegisterOrderExecutionServiceServer(s grpc.ServiceRegistrar, srv OrderExecutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderExecutionService_ServiceDesc, srv)
}

func _OrderExecutionService_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExecutionServiceServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExecutionService_SubmitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExecutionServiceServer).SubmitOrder(ctx, req.(*SubmitOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderExecutionService_SubmitOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderExecutionServiceServer).SubmitOrders(&grpc.GenericServerStream[SubmitOrder, SubmitOrderResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderExecutionService_SubmitOrdersServer = grpc.BidiStreamingServer[SubmitOrder, SubmitOrderResult]

func _OrderExecutionService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExecutionServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExecutionService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExecutionServiceServer).CancelOrder(ctx, req.(*CancelOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderExecutionService_ModifyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExecutionServiceServer).ModifyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExecutionService_ModifyOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExecutionServiceServer).ModifyOrder(ctx, req.(*ModifyOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderExecutionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExecutionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExecutionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExecutionServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderExecutionService_ServiceDesc is the grpc.ServiceDesc for OrderExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reef.contracts.orderexecution.v1.OrderExecutionService",
	HandlerType: (*OrderExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _OrderExecutionService_SubmitOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderExecutionService_CancelOrder_Handler,
		},
		{
			MethodName: "ModifyOrder",
			Handler:    _OrderExecutionService_ModifyOrder_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _OrderExecutionService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitOrders",
			Handler:       _OrderExecutionService_SubmitOrders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "contracts/proto/order_execution.proto",
}
