// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/order_execution.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.orderexecution.v1;

/**
 * Protobuf type {@code reef.contracts.orderexecution.v1.CommandMetadata}
 */
@com.google.protobuf.Generated
public final class CommandMetadata extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:reef.contracts.orderexecution.v1.CommandMetadata)
    CommandMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "CommandMetadata");
  }
  // Use CommandMetadata.newBuilder() to construct.
  private CommandMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CommandMetadata() {
    commandId_ = "";
    correlationId_ = "";
    actorId_ = "";
    actorType_ = "";
    occurredAt_ = "";
    traceId_ = "";
    causationId_ = "";
    runId_ = "";
    venueSessionId_ = "";
    clientOrderId_ = "";
    botId_ = "";
    botVersion_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_CommandMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_CommandMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            reef.contracts.orderexecution.v1.CommandMetadata.class, reef.contracts.orderexecution.v1.CommandMetadata.Builder.class);
  }

  public static final int COMMAND_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commandId_ = "";
  /**
   * <code>string command_id = 1;</code>
   * @return The commandId.
   */
  @java.lang.Override
  public java.lang.String getCommandId() {
    java.lang.Object ref = commandId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commandId_ = s;
      return s;
    }
  }
  /**
   * <code>string command_id = 1;</code>
   * @return The bytes for commandId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandIdBytes() {
    java.lang.Object ref = commandId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commandId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CORRELATION_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object correlationId_ = "";
  /**
   * <code>string correlation_id = 2;</code>
   * @return The correlationId.
   */
  @java.lang.Override
  public java.lang.String getCorrelationId() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      correlationId_ = s;
      return s;
    }
  }
  /**
   * <code>string correlation_id = 2;</code>
   * @return The bytes for correlationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCorrelationIdBytes() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      correlationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTOR_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actorId_ = "";
  /**
   * <code>string actor_id = 3;</code>
   * @return The actorId.
   */
  @java.lang.Override
  public java.lang.String getActorId() {
    java.lang.Object ref = actorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actorId_ = s;
      return s;
    }
  }
  /**
   * <code>string actor_id = 3;</code>
   * @return The bytes for actorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorIdBytes() {
    java.lang.Object ref = actorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTOR_TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actorType_ = "";
  /**
   * <code>string actor_type = 4;</code>
   * @return The actorType.
   */
  @java.lang.Override
  public java.lang.String getActorType() {
    java.lang.Object ref = actorType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actorType_ = s;
      return s;
    }
  }
  /**
   * <code>string actor_type = 4;</code>
   * @return The bytes for actorType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorTypeBytes() {
    java.lang.Object ref = actorType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actorType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OCCURRED_AT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object occurredAt_ = "";
  /**
   * <code>string occurred_at = 5;</code>
   * @return The occurredAt.
   */
  @java.lang.Override
  public java.lang.String getOccurredAt() {
    java.lang.Object ref = occurredAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      occurredAt_ = s;
      return s;
    }
  }
  /**
   * <code>string occurred_at = 5;</code>
   * @return The bytes for occurredAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOccurredAtBytes() {
    java.lang.Object ref = occurredAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      occurredAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACE_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceId_ = "";
  /**
   * <code>string trace_id = 6;</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <code>string trace_id = 6;</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAUSATION_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object causationId_ = "";
  /**
   * <code>string causation_id = 7;</code>
   * @return The causationId.
   */
  @java.lang.Override
  public java.lang.String getCausationId() {
    java.lang.Object ref = causationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      causationId_ = s;
      return s;
    }
  }
  /**
   * <code>string causation_id = 7;</code>
   * @return The bytes for causationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCausationIdBytes() {
    java.lang.Object ref = causationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      causationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUN_ID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object runId_ = "";
  /**
   * <code>string run_id = 8;</code>
   * @return The runId.
   */
  @java.lang.Override
  public java.lang.String getRunId() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      runId_ = s;
      return s;
    }
  }
  /**
   * <code>string run_id = 8;</code>
   * @return The bytes for runId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRunIdBytes() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      runId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VENUE_SESSION_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object venueSessionId_ = "";
  /**
   * <code>string venue_session_id = 9;</code>
   * @return The venueSessionId.
   */
  @java.lang.Override
  public java.lang.String getVenueSessionId() {
    java.lang.Object ref = venueSessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      venueSessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string venue_session_id = 9;</code>
   * @return The bytes for venueSessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVenueSessionIdBytes() {
    java.lang.Object ref = venueSessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      venueSessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_ORDER_ID_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientOrderId_ = "";
  /**
   * <code>string client_order_id = 10;</code>
   * @return The clientOrderId.
   */
  @java.lang.Override
  public java.lang.String getClientOrderId() {
    java.lang.Object ref = clientOrderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientOrderId_ = s;
      return s;
    }
  }
  /**
   * <code>string client_order_id = 10;</code>
   * @return The bytes for clientOrderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientOrderIdBytes() {
    java.lang.Object ref = clientOrderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientOrderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOT_ID_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object botId_ = "";
  /**
   * <code>string bot_id = 11;</code>
   * @return The botId.
   */
  @java.lang.Override
  public java.lang.String getBotId() {
    java.lang.Object ref = botId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      botId_ = s;
      return s;
    }
  }
  /**
   * <code>string bot_id = 11;</code>
   * @return The bytes for botId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBotIdBytes() {
    java.lang.Object ref = botId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      botId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOT_VERSION_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object botVersion_ = "";
  /**
   * <code>string bot_version = 12;</code>
   * @return The botVersion.
   */
  @java.lang.Override
  public java.lang.String getBotVersion() {
    java.lang.Object ref = botVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      botVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string bot_version = 12;</code>
   * @return The bytes for botVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBotVersionBytes() {
    java.lang.Object ref = botVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      botVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(commandId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, commandId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(correlationId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, correlationId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, actorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, actorType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(occurredAt_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, occurredAt_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, traceId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(causationId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, causationId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(runId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, runId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(venueSessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, venueSessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientOrderId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, clientOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(botId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, botId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(botVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, botVersion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(commandId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, commandId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(correlationId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, correlationId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, actorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, actorType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(occurredAt_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, occurredAt_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, traceId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(causationId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, causationId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(runId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, runId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(venueSessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, venueSessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientOrderId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, clientOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(botId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, botId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(botVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, botVersion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof reef.contracts.orderexecution.v1.CommandMetadata)) {
      return super.equals(obj);
    }
    reef.contracts.orderexecution.v1.CommandMetadata other = (reef.contracts.orderexecution.v1.CommandMetadata) obj;

    if (!getCommandId()
        .equals(other.getCommandId())) return false;
    if (!getCorrelationId()
        .equals(other.getCorrelationId())) return false;
    if (!getActorId()
        .equals(other.getActorId())) return false;
    if (!getActorType()
        .equals(other.getActorType())) return false;
    if (!getOccurredAt()
        .equals(other.getOccurredAt())) return false;
    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (!getCausationId()
        .equals(other.getCausationId())) return false;
    if (!getRunId()
        .equals(other.getRunId())) return false;
    if (!getVenueSessionId()
        .equals(other.getVenueSessionId())) return false;
    if (!getClientOrderId()
        .equals(other.getClientOrderId())) return false;
    if (!getBotId()
        .equals(other.getBotId())) return false;
    if (!getBotVersion()
        .equals(other.getBotVersion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCommandId().hashCode();
    hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationId().hashCode();
    hash = (37 * hash) + ACTOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getActorId().hashCode();
    hash = (37 * hash) + ACTOR_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getActorType().hashCode();
    hash = (37 * hash) + OCCURRED_AT_FIELD_NUMBER;
    hash = (53 * hash) + getOccurredAt().hashCode();
    hash = (37 * hash) + TRACE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (37 * hash) + CAUSATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCausationId().hashCode();
    hash = (37 * hash) + RUN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRunId().hashCode();
    hash = (37 * hash) + VENUE_SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getVenueSessionId().hashCode();
    hash = (37 * hash) + CLIENT_ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientOrderId().hashCode();
    hash = (37 * hash) + BOT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBotId().hashCode();
    hash = (37 * hash) + BOT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getBotVersion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static reef.contracts.orderexecution.v1.CommandMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static reef.contracts.orderexecution.v1.CommandMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.orderexecution.v1.CommandMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(reef.contracts.orderexecution.v1.CommandMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reef.contracts.orderexecution.v1.CommandMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reef.contracts.orderexecution.v1.CommandMetadata)
      reef.contracts.orderexecution.v1.CommandMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_CommandMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_CommandMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              reef.contracts.orderexecution.v1.CommandMetadata.class, reef.contracts.orderexecution.v1.CommandMetadata.Builder.class);
    }

    // Construct using reef.contracts.orderexecution.v1.CommandMetadata.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commandId_ = "";
      correlationId_ = "";
      actorId_ = "";
      actorType_ = "";
      occurredAt_ = "";
      traceId_ = "";
      causationId_ = "";
      runId_ = "";
      venueSessionId_ = "";
      clientOrderId_ = "";
      botId_ = "";
      botVersion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_CommandMetadata_descriptor;
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.CommandMetadata getDefaultInstanceForType() {
      return reef.contracts.orderexecution.v1.CommandMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.CommandMetadata build() {
      reef.contracts.orderexecution.v1.CommandMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.CommandMetadata buildPartial() {
      reef.contracts.orderexecution.v1.CommandMetadata result = new reef.contracts.orderexecution.v1.CommandMetadata(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(reef.contracts.orderexecution.v1.CommandMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.commandId_ = commandId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.correlationId_ = correlationId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.actorId_ = actorId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.actorType_ = actorType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.occurredAt_ = occurredAt_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.traceId_ = traceId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.causationId_ = causationId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.runId_ = runId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.venueSessionId_ = venueSessionId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.clientOrderId_ = clientOrderId_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.botId_ = botId_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.botVersion_ = botVersion_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof reef.contracts.orderexecution.v1.CommandMetadata) {
        return mergeFrom((reef.contracts.orderexecution.v1.CommandMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(reef.contracts.orderexecution.v1.CommandMetadata other) {
      if (other == reef.contracts.orderexecution.v1.CommandMetadata.getDefaultInstance()) return this;
      if (!other.getCommandId().isEmpty()) {
        commandId_ = other.commandId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCorrelationId().isEmpty()) {
        correlationId_ = other.correlationId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getActorId().isEmpty()) {
        actorId_ = other.actorId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getActorType().isEmpty()) {
        actorType_ = other.actorType_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getOccurredAt().isEmpty()) {
        occurredAt_ = other.occurredAt_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getCausationId().isEmpty()) {
        causationId_ = other.causationId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getRunId().isEmpty()) {
        runId_ = other.runId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getVenueSessionId().isEmpty()) {
        venueSessionId_ = other.venueSessionId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getClientOrderId().isEmpty()) {
        clientOrderId_ = other.clientOrderId_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getBotId().isEmpty()) {
        botId_ = other.botId_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getBotVersion().isEmpty()) {
        botVersion_ = other.botVersion_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              commandId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              correlationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              actorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              actorType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              occurredAt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              traceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              causationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              runId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              venueSessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              clientOrderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              botId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              botVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object commandId_ = "";
    /**
     * <code>string command_id = 1;</code>
     * @return The commandId.
     */
    public java.lang.String getCommandId() {
      java.lang.Object ref = commandId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string command_id = 1;</code>
     * @return The bytes for commandId.
     */
    public com.google.protobuf.ByteString
        getCommandIdBytes() {
      java.lang.Object ref = commandId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string command_id = 1;</code>
     * @param value The commandId to set.
     * @return This builder for chaining.
     */
    public Builder setCommandId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commandId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string command_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandId() {
      commandId_ = getDefaultInstance().getCommandId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string command_id = 1;</code>
     * @param value The bytes for commandId to set.
     * @return This builder for chaining.
     */
    public Builder setCommandIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commandId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object correlationId_ = "";
    /**
     * <code>string correlation_id = 2;</code>
     * @return The correlationId.
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string correlation_id = 2;</code>
     * @return The bytes for correlationId.
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string correlation_id = 2;</code>
     * @param value The correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      correlationId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string correlation_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationId() {
      correlationId_ = getDefaultInstance().getCorrelationId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string correlation_id = 2;</code>
     * @param value The bytes for correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      correlationId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object actorId_ = "";
    /**
     * <code>string actor_id = 3;</code>
     * @return The actorId.
     */
    public java.lang.String getActorId() {
      java.lang.Object ref = actorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string actor_id = 3;</code>
     * @return The bytes for actorId.
     */
    public com.google.protobuf.ByteString
        getActorIdBytes() {
      java.lang.Object ref = actorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string actor_id = 3;</code>
     * @param value The actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string actor_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearActorId() {
      actorId_ = getDefaultInstance().getActorId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string actor_id = 3;</code>
     * @param value The bytes for actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object actorType_ = "";
    /**
     * <code>string actor_type = 4;</code>
     * @return The actorType.
     */
    public java.lang.String getActorType() {
      java.lang.Object ref = actorType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actorType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string actor_type = 4;</code>
     * @return The bytes for actorType.
     */
    public com.google.protobuf.ByteString
        getActorTypeBytes() {
      java.lang.Object ref = actorType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string actor_type = 4;</code>
     * @param value The actorType to set.
     * @return This builder for chaining.
     */
    public Builder setActorType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actorType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string actor_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearActorType() {
      actorType_ = getDefaultInstance().getActorType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string actor_type = 4;</code>
     * @param value The bytes for actorType to set.
     * @return This builder for chaining.
     */
    public Builder setActorTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actorType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object occurredAt_ = "";
    /**
     * <code>string occurred_at = 5;</code>
     * @return The occurredAt.
     */
    public java.lang.String getOccurredAt() {
      java.lang.Object ref = occurredAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        occurredAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string occurred_at = 5;</code>
     * @return The bytes for occurredAt.
     */
    public com.google.protobuf.ByteString
        getOccurredAtBytes() {
      java.lang.Object ref = occurredAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        occurredAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string occurred_at = 5;</code>
     * @param value The occurredAt to set.
     * @return This builder for chaining.
     */
    public Builder setOccurredAt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      occurredAt_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string occurred_at = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOccurredAt() {
      occurredAt_ = getDefaultInstance().getOccurredAt();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string occurred_at = 5;</code>
     * @param value The bytes for occurredAt to set.
     * @return This builder for chaining.
     */
    public Builder setOccurredAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      occurredAt_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <code>string trace_id = 6;</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string trace_id = 6;</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string trace_id = 6;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string trace_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      traceId_ = getDefaultInstance().getTraceId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string trace_id = 6;</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object causationId_ = "";
    /**
     * <code>string causation_id = 7;</code>
     * @return The causationId.
     */
    public java.lang.String getCausationId() {
      java.lang.Object ref = causationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        causationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string causation_id = 7;</code>
     * @return The bytes for causationId.
     */
    public com.google.protobuf.ByteString
        getCausationIdBytes() {
      java.lang.Object ref = causationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        causationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string causation_id = 7;</code>
     * @param value The causationId to set.
     * @return This builder for chaining.
     */
    public Builder setCausationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      causationId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string causation_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCausationId() {
      causationId_ = getDefaultInstance().getCausationId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string causation_id = 7;</code>
     * @param value The bytes for causationId to set.
     * @return This builder for chaining.
     */
    public Builder setCausationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      causationId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object runId_ = "";
    /**
     * <code>string run_id = 8;</code>
     * @return The runId.
     */
    public java.lang.String getRunId() {
      java.lang.Object ref = runId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        runId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string run_id = 8;</code>
     * @return The bytes for runId.
     */
    public com.google.protobuf.ByteString
        getRunIdBytes() {
      java.lang.Object ref = runId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string run_id = 8;</code>
     * @param value The runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      runId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string run_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunId() {
      runId_ = getDefaultInstance().getRunId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string run_id = 8;</code>
     * @param value The bytes for runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      runId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object venueSessionId_ = "";
    /**
     * <code>string venue_session_id = 9;</code>
     * @return The venueSessionId.
     */
    public java.lang.String getVenueSessionId() {
      java.lang.Object ref = venueSessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        venueSessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string venue_session_id = 9;</code>
     * @return The bytes for venueSessionId.
     */
    public com.google.protobuf.ByteString
        getVenueSessionIdBytes() {
      java.lang.Object ref = venueSessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        venueSessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string venue_session_id = 9;</code>
     * @param value The venueSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setVenueSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      venueSessionId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string venue_session_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearVenueSessionId() {
      venueSessionId_ = getDefaultInstance().getVenueSessionId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string venue_session_id = 9;</code>
     * @param value The bytes for venueSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setVenueSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      venueSessionId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object clientOrderId_ = "";
    /**
     * <code>string client_order_id = 10;</code>
     * @return The clientOrderId.
     */
    public java.lang.String getClientOrderId() {
      java.lang.Object ref = clientOrderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientOrderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_order_id = 10;</code>
     * @return The bytes for clientOrderId.
     */
    public com.google.protobuf.ByteString
        getClientOrderIdBytes() {
      java.lang.Object ref = clientOrderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_order_id = 10;</code>
     * @param value The clientOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setClientOrderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientOrderId_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string client_order_id = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientOrderId() {
      clientOrderId_ = getDefaultInstance().getClientOrderId();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string client_order_id = 10;</code>
     * @param value The bytes for clientOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setClientOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientOrderId_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object botId_ = "";
    /**
     * <code>string bot_id = 11;</code>
     * @return The botId.
     */
    public java.lang.String getBotId() {
      java.lang.Object ref = botId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        botId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bot_id = 11;</code>
     * @return The bytes for botId.
     */
    public com.google.protobuf.ByteString
        getBotIdBytes() {
      java.lang.Object ref = botId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        botId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bot_id = 11;</code>
     * @param value The botId to set.
     * @return This builder for chaining.
     */
    public Builder setBotId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      botId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string bot_id = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearBotId() {
      botId_ = getDefaultInstance().getBotId();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string bot_id = 11;</code>
     * @param value The bytes for botId to set.
     * @return This builder for chaining.
     */
    public Builder setBotIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      botId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object botVersion_ = "";
    /**
     * <code>string bot_version = 12;</code>
     * @return The botVersion.
     */
    public java.lang.String getBotVersion() {
      java.lang.Object ref = botVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        botVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bot_version = 12;</code>
     * @return The bytes for botVersion.
     */
    public com.google.protobuf.ByteString
        getBotVersionBytes() {
      java.lang.Object ref = botVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        botVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bot_version = 12;</code>
     * @param value The botVersion to set.
     * @return This builder for chaining.
     */
    public Builder setBotVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      botVersion_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string bot_version = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearBotVersion() {
      botVersion_ = getDefaultInstance().getBotVersion();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string bot_version = 12;</code>
     * @param value The bytes for botVersion to set.
     * @return This builder for chaining.
     */
    public Builder setBotVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      botVersion_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:reef.contracts.orderexecution.v1.CommandMetadata)
  }

  // @@protoc_insertion_point(class_scope:reef.contracts.orderexecution.v1.CommandMetadata)
  private static final reef.contracts.orderexecution.v1.CommandMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new reef.contracts.orderexecution.v1.CommandMetadata();
  }

  public static reef.contracts.orderexecution.v1.CommandMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandMetadata>
      PARSER = new com.google.protobuf.AbstractParser<CommandMetadata>() {
    @java.lang.Override
    public CommandMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CommandMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public reef.contracts.orderexecution.v1.CommandMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

