// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/order_execution.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.orderexecution.v1;

@com.google.protobuf.Generated
public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reef.contracts.orderexecution.v1.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {
}
