// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/order_execution.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.orderexecution.v1;

@com.google.protobuf.Generated
public interface ModifyOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reef.contracts.orderexecution.v1.ModifyOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
   * @return The metadata.
   */
  reef.contracts.orderexecution.v1.CommandMetadata getMetadata();
  /**
   * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
   */
  reef.contracts.orderexecution.v1.CommandMetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>string order_id = 2;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 2;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 3;</code>
   * @return Whether the quantity field is set.
   */
  boolean hasQuantity();
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 3;</code>
   * @return The quantity.
   */
  reef.contracts.orderexecution.v1.OrderQuantity getQuantity();
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 3;</code>
   */
  reef.contracts.orderexecution.v1.OrderQuantityOrBuilder getQuantityOrBuilder();

  /**
   * <code>.reef.contracts.orderexecution.v1.Price limit_price = 4;</code>
   * @return Whether the limitPrice field is set.
   */
  boolean hasLimitPrice();
  /**
   * <code>.reef.contracts.orderexecution.v1.Price limit_price = 4;</code>
   * @return The limitPrice.
   */
  reef.contracts.orderexecution.v1.Price getLimitPrice();
  /**
   * <code>.reef.contracts.orderexecution.v1.Price limit_price = 4;</code>
   */
  reef.contracts.orderexecution.v1.PriceOrBuilder getLimitPriceOrBuilder();
}
