// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/order_execution.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.orderexecution.v1;

@com.google.protobuf.Generated
public interface OrderQuantityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reef.contracts.orderexecution.v1.OrderQuantity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string units = 1;</code>
   * @return The units.
   */
  java.lang.String getUnits();
  /**
   * <code>string units = 1;</code>
   * @return The bytes for units.
   */
  com.google.protobuf.ByteString
      getUnitsBytes();
}
