// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/order_execution.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.orderexecution.v1;

/**
 * Protobuf type {@code reef.contracts.orderexecution.v1.OrderAccepted}
 */
@com.google.protobuf.Generated
public final class OrderAccepted extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:reef.contracts.orderexecution.v1.OrderAccepted)
    OrderAcceptedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "OrderAccepted");
  }
  // Use OrderAccepted.newBuilder() to construct.
  private OrderAccepted(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OrderAccepted() {
    eventId_ = "";
    orderId_ = "";
    engineOrderId_ = "";
    occurredAt_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_OrderAccepted_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_OrderAccepted_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            reef.contracts.orderexecution.v1.OrderAccepted.class, reef.contracts.orderexecution.v1.OrderAccepted.Builder.class);
  }

  public static final int EVENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventId_ = "";
  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  @java.lang.Override
  public java.lang.String getEventId() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventId_ = s;
      return s;
    }
  }
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventIdBytes() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object orderId_ = "";
  /**
   * <code>string order_id = 2;</code>
   * @return The orderId.
   */
  @java.lang.Override
  public java.lang.String getOrderId() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderId_ = s;
      return s;
    }
  }
  /**
   * <code>string order_id = 2;</code>
   * @return The bytes for orderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrderIdBytes() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENGINE_ORDER_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object engineOrderId_ = "";
  /**
   * <code>string engine_order_id = 3;</code>
   * @return The engineOrderId.
   */
  @java.lang.Override
  public java.lang.String getEngineOrderId() {
    java.lang.Object ref = engineOrderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      engineOrderId_ = s;
      return s;
    }
  }
  /**
   * <code>string engine_order_id = 3;</code>
   * @return The bytes for engineOrderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEngineOrderIdBytes() {
    java.lang.Object ref = engineOrderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      engineOrderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OCCURRED_AT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object occurredAt_ = "";
  /**
   * <code>string occurred_at = 4;</code>
   * @return The occurredAt.
   */
  @java.lang.Override
  public java.lang.String getOccurredAt() {
    java.lang.Object ref = occurredAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      occurredAt_ = s;
      return s;
    }
  }
  /**
   * <code>string occurred_at = 4;</code>
   * @return The bytes for occurredAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOccurredAtBytes() {
    java.lang.Object ref = occurredAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      occurredAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(orderId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, orderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(engineOrderId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, engineOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(occurredAt_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, occurredAt_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(orderId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, orderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(engineOrderId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, engineOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(occurredAt_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, occurredAt_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof reef.contracts.orderexecution.v1.OrderAccepted)) {
      return super.equals(obj);
    }
    reef.contracts.orderexecution.v1.OrderAccepted other = (reef.contracts.orderexecution.v1.OrderAccepted) obj;

    if (!getEventId()
        .equals(other.getEventId())) return false;
    if (!getOrderId()
        .equals(other.getOrderId())) return false;
    if (!getEngineOrderId()
        .equals(other.getEngineOrderId())) return false;
    if (!getOccurredAt()
        .equals(other.getOccurredAt())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventId().hashCode();
    hash = (37 * hash) + ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderId().hashCode();
    hash = (37 * hash) + ENGINE_ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEngineOrderId().hashCode();
    hash = (37 * hash) + OCCURRED_AT_FIELD_NUMBER;
    hash = (53 * hash) + getOccurredAt().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static reef.contracts.orderexecution.v1.OrderAccepted parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static reef.contracts.orderexecution.v1.OrderAccepted parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.orderexecution.v1.OrderAccepted parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(reef.contracts.orderexecution.v1.OrderAccepted prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reef.contracts.orderexecution.v1.OrderAccepted}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reef.contracts.orderexecution.v1.OrderAccepted)
      reef.contracts.orderexecution.v1.OrderAcceptedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_OrderAccepted_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_OrderAccepted_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              reef.contracts.orderexecution.v1.OrderAccepted.class, reef.contracts.orderexecution.v1.OrderAccepted.Builder.class);
    }

    // Construct using reef.contracts.orderexecution.v1.OrderAccepted.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventId_ = "";
      orderId_ = "";
      engineOrderId_ = "";
      occurredAt_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_OrderAccepted_descriptor;
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.OrderAccepted getDefaultInstanceForType() {
      return reef.contracts.orderexecution.v1.OrderAccepted.getDefaultInstance();
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.OrderAccepted build() {
      reef.contracts.orderexecution.v1.OrderAccepted result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.OrderAccepted buildPartial() {
      reef.contracts.orderexecution.v1.OrderAccepted result = new reef.contracts.orderexecution.v1.OrderAccepted(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(reef.contracts.orderexecution.v1.OrderAccepted result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventId_ = eventId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.orderId_ = orderId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.engineOrderId_ = engineOrderId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.occurredAt_ = occurredAt_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof reef.contracts.orderexecution.v1.OrderAccepted) {
        return mergeFrom((reef.contracts.orderexecution.v1.OrderAccepted)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(reef.contracts.orderexecution.v1.OrderAccepted other) {
      if (other == reef.contracts.orderexecution.v1.OrderAccepted.getDefaultInstance()) return this;
      if (!other.getEventId().isEmpty()) {
        eventId_ = other.eventId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getOrderId().isEmpty()) {
        orderId_ = other.orderId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEngineOrderId().isEmpty()) {
        engineOrderId_ = other.engineOrderId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getOccurredAt().isEmpty()) {
        occurredAt_ = other.occurredAt_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              orderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              engineOrderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              occurredAt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventId_ = "";
    /**
     * <code>string event_id = 1;</code>
     * @return The eventId.
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_id = 1;</code>
     * @return The bytes for eventId.
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      eventId_ = getDefaultInstance().getEventId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The bytes for eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object orderId_ = "";
    /**
     * <code>string order_id = 2;</code>
     * @return The orderId.
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string order_id = 2;</code>
     * @return The bytes for orderId.
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string order_id = 2;</code>
     * @param value The orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      orderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string order_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderId() {
      orderId_ = getDefaultInstance().getOrderId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string order_id = 2;</code>
     * @param value The bytes for orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object engineOrderId_ = "";
    /**
     * <code>string engine_order_id = 3;</code>
     * @return The engineOrderId.
     */
    public java.lang.String getEngineOrderId() {
      java.lang.Object ref = engineOrderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engineOrderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string engine_order_id = 3;</code>
     * @return The bytes for engineOrderId.
     */
    public com.google.protobuf.ByteString
        getEngineOrderIdBytes() {
      java.lang.Object ref = engineOrderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engineOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string engine_order_id = 3;</code>
     * @param value The engineOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setEngineOrderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      engineOrderId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string engine_order_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEngineOrderId() {
      engineOrderId_ = getDefaultInstance().getEngineOrderId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string engine_order_id = 3;</code>
     * @param value The bytes for engineOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setEngineOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      engineOrderId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object occurredAt_ = "";
    /**
     * <code>string occurred_at = 4;</code>
     * @return The occurredAt.
     */
    public java.lang.String getOccurredAt() {
      java.lang.Object ref = occurredAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        occurredAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string occurred_at = 4;</code>
     * @return The bytes for occurredAt.
     */
    public com.google.protobuf.ByteString
        getOccurredAtBytes() {
      java.lang.Object ref = occurredAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        occurredAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string occurred_at = 4;</code>
     * @param value The occurredAt to set.
     * @return This builder for chaining.
     */
    public Builder setOccurredAt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      occurredAt_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string occurred_at = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOccurredAt() {
      occurredAt_ = getDefaultInstance().getOccurredAt();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string occurred_at = 4;</code>
     * @param value The bytes for occurredAt to set.
     * @return This builder for chaining.
     */
    public Builder setOccurredAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      occurredAt_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:reef.contracts.orderexecution.v1.OrderAccepted)
  }

  // @@protoc_insertion_point(class_scope:reef.contracts.orderexecution.v1.OrderAccepted)
  private static final reef.contracts.orderexecution.v1.OrderAccepted DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new reef.contracts.orderexecution.v1.OrderAccepted();
  }

  public static reef.contracts.orderexecution.v1.OrderAccepted getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderAccepted>
      PARSER = new com.google.protobuf.AbstractParser<OrderAccepted>() {
    @java.lang.Override
    public OrderAccepted parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OrderAccepted> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderAccepted> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public reef.contracts.orderexecution.v1.OrderAccepted getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

