// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/order_execution.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.orderexecution.v1;

/**
 * Protobuf type {@code reef.contracts.orderexecution.v1.SubmitOrder}
 */
@com.google.protobuf.Generated
public final class SubmitOrder extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:reef.contracts.orderexecution.v1.SubmitOrder)
    SubmitOrderOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "SubmitOrder");
  }
  // Use SubmitOrder.newBuilder() to construct.
  private SubmitOrder(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SubmitOrder() {
    orderId_ = "";
    instrumentId_ = "";
    participantId_ = "";
    accountId_ = "";
    side_ = 0;
    orderType_ = 0;
    timeInForce_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_SubmitOrder_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_SubmitOrder_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            reef.contracts.orderexecution.v1.SubmitOrder.class, reef.contracts.orderexecution.v1.SubmitOrder.Builder.class);
  }

  private int bitField0_;
  public static final int METADATA_FIELD_NUMBER = 1;
  private reef.contracts.orderexecution.v1.CommandMetadata metadata_;
  /**
   * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.CommandMetadata getMetadata() {
    return metadata_ == null ? reef.contracts.orderexecution.v1.CommandMetadata.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.CommandMetadataOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? reef.contracts.orderexecution.v1.CommandMetadata.getDefaultInstance() : metadata_;
  }

  public static final int ORDER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object orderId_ = "";
  /**
   * <code>string order_id = 2;</code>
   * @return The orderId.
   */
  @java.lang.Override
  public java.lang.String getOrderId() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderId_ = s;
      return s;
    }
  }
  /**
   * <code>string order_id = 2;</code>
   * @return The bytes for orderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrderIdBytes() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTRUMENT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instrumentId_ = "";
  /**
   * <code>string instrument_id = 3;</code>
   * @return The instrumentId.
   */
  @java.lang.Override
  public java.lang.String getInstrumentId() {
    java.lang.Object ref = instrumentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instrumentId_ = s;
      return s;
    }
  }
  /**
   * <code>string instrument_id = 3;</code>
   * @return The bytes for instrumentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstrumentIdBytes() {
    java.lang.Object ref = instrumentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instrumentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTICIPANT_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object participantId_ = "";
  /**
   * <code>string participant_id = 4;</code>
   * @return The participantId.
   */
  @java.lang.Override
  public java.lang.String getParticipantId() {
    java.lang.Object ref = participantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      participantId_ = s;
      return s;
    }
  }
  /**
   * <code>string participant_id = 4;</code>
   * @return The bytes for participantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParticipantIdBytes() {
    java.lang.Object ref = participantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      participantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accountId_ = "";
  /**
   * <code>string account_id = 5;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public java.lang.String getAccountId() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountId_ = s;
      return s;
    }
  }
  /**
   * <code>string account_id = 5;</code>
   * @return The bytes for accountId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountIdBytes() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIDE_FIELD_NUMBER = 6;
  private int side_ = 0;
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderSide side = 6;</code>
   * @return The enum numeric value on the wire for side.
   */
  @java.lang.Override public int getSideValue() {
    return side_;
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderSide side = 6;</code>
   * @return The side.
   */
  @java.lang.Override public reef.contracts.orderexecution.v1.OrderSide getSide() {
    reef.contracts.orderexecution.v1.OrderSide result = reef.contracts.orderexecution.v1.OrderSide.forNumber(side_);
    return result == null ? reef.contracts.orderexecution.v1.OrderSide.UNRECOGNIZED : result;
  }

  public static final int ORDER_TYPE_FIELD_NUMBER = 7;
  private int orderType_ = 0;
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderType order_type = 7;</code>
   * @return The enum numeric value on the wire for orderType.
   */
  @java.lang.Override public int getOrderTypeValue() {
    return orderType_;
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderType order_type = 7;</code>
   * @return The orderType.
   */
  @java.lang.Override public reef.contracts.orderexecution.v1.OrderType getOrderType() {
    reef.contracts.orderexecution.v1.OrderType result = reef.contracts.orderexecution.v1.OrderType.forNumber(orderType_);
    return result == null ? reef.contracts.orderexecution.v1.OrderType.UNRECOGNIZED : result;
  }

  public static final int QUANTITY_FIELD_NUMBER = 8;
  private reef.contracts.orderexecution.v1.OrderQuantity quantity_;
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
   * @return Whether the quantity field is set.
   */
  @java.lang.Override
  public boolean hasQuantity() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.OrderQuantity getQuantity() {
    return quantity_ == null ? reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance() : quantity_;
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.OrderQuantityOrBuilder getQuantityOrBuilder() {
    return quantity_ == null ? reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance() : quantity_;
  }

  public static final int LIMIT_PRICE_FIELD_NUMBER = 9;
  private reef.contracts.orderexecution.v1.Price limitPrice_;
  /**
   * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
   * @return Whether the limitPrice field is set.
   */
  @java.lang.Override
  public boolean hasLimitPrice() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
   * @return The limitPrice.
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.Price getLimitPrice() {
    return limitPrice_ == null ? reef.contracts.orderexecution.v1.Price.getDefaultInstance() : limitPrice_;
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.PriceOrBuilder getLimitPriceOrBuilder() {
    return limitPrice_ == null ? reef.contracts.orderexecution.v1.Price.getDefaultInstance() : limitPrice_;
  }

  public static final int TIME_IN_FORCE_FIELD_NUMBER = 10;
  private int timeInForce_ = 0;
  /**
   * <code>.reef.contracts.orderexecution.v1.TimeInForce time_in_force = 10;</code>
   * @return The enum numeric value on the wire for timeInForce.
   */
  @java.lang.Override public int getTimeInForceValue() {
    return timeInForce_;
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.TimeInForce time_in_force = 10;</code>
   * @return The timeInForce.
   */
  @java.lang.Override public reef.contracts.orderexecution.v1.TimeInForce getTimeInForce() {
    reef.contracts.orderexecution.v1.TimeInForce result = reef.contracts.orderexecution.v1.TimeInForce.forNumber(timeInForce_);
    return result == null ? reef.contracts.orderexecution.v1.TimeInForce.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMetadata());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(orderId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, orderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instrumentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, instrumentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(participantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, participantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, accountId_);
    }
    if (side_ != reef.contracts.orderexecution.v1.OrderSide.ORDER_SIDE_UNSPECIFIED.getNumber()) {
      output.writeEnum(6, side_);
    }
    if (orderType_ != reef.contracts.orderexecution.v1.OrderType.ORDER_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(7, orderType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(8, getQuantity());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(9, getLimitPrice());
    }
    if (timeInForce_ != reef.contracts.orderexecution.v1.TimeInForce.TIME_IN_FORCE_UNSPECIFIED.getNumber()) {
      output.writeEnum(10, timeInForce_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMetadata());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(orderId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, orderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instrumentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, instrumentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(participantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, participantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, accountId_);
    }
    if (side_ != reef.contracts.orderexecution.v1.OrderSide.ORDER_SIDE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, side_);
    }
    if (orderType_ != reef.contracts.orderexecution.v1.OrderType.ORDER_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, orderType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getQuantity());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getLimitPrice());
    }
    if (timeInForce_ != reef.contracts.orderexecution.v1.TimeInForce.TIME_IN_FORCE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, timeInForce_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof reef.contracts.orderexecution.v1.SubmitOrder)) {
      return super.equals(obj);
    }
    reef.contracts.orderexecution.v1.SubmitOrder other = (reef.contracts.orderexecution.v1.SubmitOrder) obj;

    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getOrderId()
        .equals(other.getOrderId())) return false;
    if (!getInstrumentId()
        .equals(other.getInstrumentId())) return false;
    if (!getParticipantId()
        .equals(other.getParticipantId())) return false;
    if (!getAccountId()
        .equals(other.getAccountId())) return false;
    if (side_ != other.side_) return false;
    if (orderType_ != other.orderType_) return false;
    if (hasQuantity() != other.hasQuantity()) return false;
    if (hasQuantity()) {
      if (!getQuantity()
          .equals(other.getQuantity())) return false;
    }
    if (hasLimitPrice() != other.hasLimitPrice()) return false;
    if (hasLimitPrice()) {
      if (!getLimitPrice()
          .equals(other.getLimitPrice())) return false;
    }
    if (timeInForce_ != other.timeInForce_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (37 * hash) + ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderId().hashCode();
    hash = (37 * hash) + INSTRUMENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInstrumentId().hashCode();
    hash = (37 * hash) + PARTICIPANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getParticipantId().hashCode();
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId().hashCode();
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + side_;
    hash = (37 * hash) + ORDER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + orderType_;
    if (hasQuantity()) {
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity().hashCode();
    }
    if (hasLimitPrice()) {
      hash = (37 * hash) + LIMIT_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getLimitPrice().hashCode();
    }
    hash = (37 * hash) + TIME_IN_FORCE_FIELD_NUMBER;
    hash = (53 * hash) + timeInForce_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static reef.contracts.orderexecution.v1.SubmitOrder parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static reef.contracts.orderexecution.v1.SubmitOrder parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.orderexecution.v1.SubmitOrder parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(reef.contracts.orderexecution.v1.SubmitOrder prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reef.contracts.orderexecution.v1.SubmitOrder}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reef.contracts.orderexecution.v1.SubmitOrder)
      reef.contracts.orderexecution.v1.SubmitOrderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_SubmitOrder_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_SubmitOrder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              reef.contracts.orderexecution.v1.SubmitOrder.class, reef.contracts.orderexecution.v1.SubmitOrder.Builder.class);
    }

    // Construct using reef.contracts.orderexecution.v1.SubmitOrder.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetMetadataFieldBuilder();
        internalGetQuantityFieldBuilder();
        internalGetLimitPriceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      orderId_ = "";
      instrumentId_ = "";
      participantId_ = "";
      accountId_ = "";
      side_ = 0;
      orderType_ = 0;
      quantity_ = null;
      if (quantityBuilder_ != null) {
        quantityBuilder_.dispose();
        quantityBuilder_ = null;
      }
      limitPrice_ = null;
      if (limitPriceBuilder_ != null) {
        limitPriceBuilder_.dispose();
        limitPriceBuilder_ = null;
      }
      timeInForce_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_SubmitOrder_descriptor;
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.SubmitOrder getDefaultInstanceForType() {
      return reef.contracts.orderexecution.v1.SubmitOrder.getDefaultInstance();
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.SubmitOrder build() {
      reef.contracts.orderexecution.v1.SubmitOrder result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.SubmitOrder buildPartial() {
      reef.contracts.orderexecution.v1.SubmitOrder result = new reef.contracts.orderexecution.v1.SubmitOrder(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(reef.contracts.orderexecution.v1.SubmitOrder result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.orderId_ = orderId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.instrumentId_ = instrumentId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.participantId_ = participantId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.accountId_ = accountId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.side_ = side_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.orderType_ = orderType_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.quantity_ = quantityBuilder_ == null
            ? quantity_
            : quantityBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.limitPrice_ = limitPriceBuilder_ == null
            ? limitPrice_
            : limitPriceBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.timeInForce_ = timeInForce_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof reef.contracts.orderexecution.v1.SubmitOrder) {
        return mergeFrom((reef.contracts.orderexecution.v1.SubmitOrder)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(reef.contracts.orderexecution.v1.SubmitOrder other) {
      if (other == reef.contracts.orderexecution.v1.SubmitOrder.getDefaultInstance()) return this;
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (!other.getOrderId().isEmpty()) {
        orderId_ = other.orderId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getInstrumentId().isEmpty()) {
        instrumentId_ = other.instrumentId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getParticipantId().isEmpty()) {
        participantId_ = other.participantId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getAccountId().isEmpty()) {
        accountId_ = other.accountId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.side_ != 0) {
        setSideValue(other.getSideValue());
      }
      if (other.orderType_ != 0) {
        setOrderTypeValue(other.getOrderTypeValue());
      }
      if (other.hasQuantity()) {
        mergeQuantity(other.getQuantity());
      }
      if (other.hasLimitPrice()) {
        mergeLimitPrice(other.getLimitPrice());
      }
      if (other.timeInForce_ != 0) {
        setTimeInForceValue(other.getTimeInForceValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              orderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              instrumentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              participantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              accountId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              side_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              orderType_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              input.readMessage(
                  internalGetQuantityFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  internalGetLimitPriceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              timeInForce_ = input.readEnum();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private reef.contracts.orderexecution.v1.CommandMetadata metadata_;
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.CommandMetadata, reef.contracts.orderexecution.v1.CommandMetadata.Builder, reef.contracts.orderexecution.v1.CommandMetadataOrBuilder> metadataBuilder_;
    /**
     * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
     * @return The metadata.
     */
    public reef.contracts.orderexecution.v1.CommandMetadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? reef.contracts.orderexecution.v1.CommandMetadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
     */
    public Builder setMetadata(reef.contracts.orderexecution.v1.CommandMetadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
     */
    public Builder setMetadata(
        reef.contracts.orderexecution.v1.CommandMetadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
     */
    public Builder mergeMetadata(reef.contracts.orderexecution.v1.CommandMetadata value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          metadata_ != null &&
          metadata_ != reef.contracts.orderexecution.v1.CommandMetadata.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
     */
    public reef.contracts.orderexecution.v1.CommandMetadata.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
     */
    public reef.contracts.orderexecution.v1.CommandMetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            reef.contracts.orderexecution.v1.CommandMetadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.CommandMetadata metadata = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.CommandMetadata, reef.contracts.orderexecution.v1.CommandMetadata.Builder, reef.contracts.orderexecution.v1.CommandMetadataOrBuilder> 
        internalGetMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            reef.contracts.orderexecution.v1.CommandMetadata, reef.contracts.orderexecution.v1.CommandMetadata.Builder, reef.contracts.orderexecution.v1.CommandMetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private java.lang.Object orderId_ = "";
    /**
     * <code>string order_id = 2;</code>
     * @return The orderId.
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string order_id = 2;</code>
     * @return The bytes for orderId.
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string order_id = 2;</code>
     * @param value The orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      orderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string order_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderId() {
      orderId_ = getDefaultInstance().getOrderId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string order_id = 2;</code>
     * @param value The bytes for orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object instrumentId_ = "";
    /**
     * <code>string instrument_id = 3;</code>
     * @return The instrumentId.
     */
    public java.lang.String getInstrumentId() {
      java.lang.Object ref = instrumentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrumentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string instrument_id = 3;</code>
     * @return The bytes for instrumentId.
     */
    public com.google.protobuf.ByteString
        getInstrumentIdBytes() {
      java.lang.Object ref = instrumentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrumentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string instrument_id = 3;</code>
     * @param value The instrumentId to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instrumentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string instrument_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstrumentId() {
      instrumentId_ = getDefaultInstance().getInstrumentId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string instrument_id = 3;</code>
     * @param value The bytes for instrumentId to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instrumentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object participantId_ = "";
    /**
     * <code>string participant_id = 4;</code>
     * @return The participantId.
     */
    public java.lang.String getParticipantId() {
      java.lang.Object ref = participantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        participantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string participant_id = 4;</code>
     * @return The bytes for participantId.
     */
    public com.google.protobuf.ByteString
        getParticipantIdBytes() {
      java.lang.Object ref = participantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        participantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string participant_id = 4;</code>
     * @param value The participantId to set.
     * @return This builder for chaining.
     */
    public Builder setParticipantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      participantId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string participant_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearParticipantId() {
      participantId_ = getDefaultInstance().getParticipantId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string participant_id = 4;</code>
     * @param value The bytes for participantId to set.
     * @return This builder for chaining.
     */
    public Builder setParticipantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      participantId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object accountId_ = "";
    /**
     * <code>string account_id = 5;</code>
     * @return The accountId.
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string account_id = 5;</code>
     * @return The bytes for accountId.
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string account_id = 5;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accountId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string account_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      accountId_ = getDefaultInstance().getAccountId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string account_id = 5;</code>
     * @param value The bytes for accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accountId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int side_ = 0;
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderSide side = 6;</code>
     * @return The enum numeric value on the wire for side.
     */
    @java.lang.Override public int getSideValue() {
      return side_;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderSide side = 6;</code>
     * @param value The enum numeric value on the wire for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideValue(int value) {
      side_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderSide side = 6;</code>
     * @return The side.
     */
    @java.lang.Override
    public reef.contracts.orderexecution.v1.OrderSide getSide() {
      reef.contracts.orderexecution.v1.OrderSide result = reef.contracts.orderexecution.v1.OrderSide.forNumber(side_);
      return result == null ? reef.contracts.orderexecution.v1.OrderSide.UNRECOGNIZED : result;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderSide side = 6;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(reef.contracts.orderexecution.v1.OrderSide value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000020;
      side_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderSide side = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      bitField0_ = (bitField0_ & ~0x00000020);
      side_ = 0;
      onChanged();
      return this;
    }

    private int orderType_ = 0;
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderType order_type = 7;</code>
     * @return The enum numeric value on the wire for orderType.
     */
    @java.lang.Override public int getOrderTypeValue() {
      return orderType_;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderType order_type = 7;</code>
     * @param value The enum numeric value on the wire for orderType to set.
     * @return This builder for chaining.
     */
    public Builder setOrderTypeValue(int value) {
      orderType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderType order_type = 7;</code>
     * @return The orderType.
     */
    @java.lang.Override
    public reef.contracts.orderexecution.v1.OrderType getOrderType() {
      reef.contracts.orderexecution.v1.OrderType result = reef.contracts.orderexecution.v1.OrderType.forNumber(orderType_);
      return result == null ? reef.contracts.orderexecution.v1.OrderType.UNRECOGNIZED : result;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderType order_type = 7;</code>
     * @param value The orderType to set.
     * @return This builder for chaining.
     */
    public Builder setOrderType(reef.contracts.orderexecution.v1.OrderType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000040;
      orderType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderType order_type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderType() {
      bitField0_ = (bitField0_ & ~0x00000040);
      orderType_ = 0;
      onChanged();
      return this;
    }

    private reef.contracts.orderexecution.v1.OrderQuantity quantity_;
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.OrderQuantity, reef.contracts.orderexecution.v1.OrderQuantity.Builder, reef.contracts.orderexecution.v1.OrderQuantityOrBuilder> quantityBuilder_;
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
     * @return Whether the quantity field is set.
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
     * @return The quantity.
     */
    public reef.contracts.orderexecution.v1.OrderQuantity getQuantity() {
      if (quantityBuilder_ == null) {
        return quantity_ == null ? reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance() : quantity_;
      } else {
        return quantityBuilder_.getMessage();
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
     */
    public Builder setQuantity(reef.contracts.orderexecution.v1.OrderQuantity value) {
      if (quantityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        quantity_ = value;
      } else {
        quantityBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
     */
    public Builder setQuantity(
        reef.contracts.orderexecution.v1.OrderQuantity.Builder builderForValue) {
      if (quantityBuilder_ == null) {
        quantity_ = builderForValue.build();
      } else {
        quantityBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
     */
    public Builder mergeQuantity(reef.contracts.orderexecution.v1.OrderQuantity value) {
      if (quantityBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          quantity_ != null &&
          quantity_ != reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance()) {
          getQuantityBuilder().mergeFrom(value);
        } else {
          quantity_ = value;
        }
      } else {
        quantityBuilder_.mergeFrom(value);
      }
      if (quantity_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000080);
      quantity_ = null;
      if (quantityBuilder_ != null) {
        quantityBuilder_.dispose();
        quantityBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
     */
    public reef.contracts.orderexecution.v1.OrderQuantity.Builder getQuantityBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return internalGetQuantityFieldBuilder().getBuilder();
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
     */
    public reef.contracts.orderexecution.v1.OrderQuantityOrBuilder getQuantityOrBuilder() {
      if (quantityBuilder_ != null) {
        return quantityBuilder_.getMessageOrBuilder();
      } else {
        return quantity_ == null ?
            reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance() : quantity_;
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.OrderQuantity, reef.contracts.orderexecution.v1.OrderQuantity.Builder, reef.contracts.orderexecution.v1.OrderQuantityOrBuilder> 
        internalGetQuantityFieldBuilder() {
      if (quantityBuilder_ == null) {
        quantityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            reef.contracts.orderexecution.v1.OrderQuantity, reef.contracts.orderexecution.v1.OrderQuantity.Builder, reef.contracts.orderexecution.v1.OrderQuantityOrBuilder>(
                getQuantity(),
                getParentForChildren(),
                isClean());
        quantity_ = null;
      }
      return quantityBuilder_;
    }

    private reef.contracts.orderexecution.v1.Price limitPrice_;
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.Price, reef.contracts.orderexecution.v1.Price.Builder, reef.contracts.orderexecution.v1.PriceOrBuilder> limitPriceBuilder_;
    /**
     * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
     * @return Whether the limitPrice field is set.
     */
    public boolean hasLimitPrice() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
     * @return The limitPrice.
     */
    public reef.contracts.orderexecution.v1.Price getLimitPrice() {
      if (limitPriceBuilder_ == null) {
        return limitPrice_ == null ? reef.contracts.orderexecution.v1.Price.getDefaultInstance() : limitPrice_;
      } else {
        return limitPriceBuilder_.getMessage();
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
     */
    public Builder setLimitPrice(reef.contracts.orderexecution.v1.Price value) {
      if (limitPriceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        limitPrice_ = value;
      } else {
        limitPriceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
     */
    public Builder setLimitPrice(
        reef.contracts.orderexecution.v1.Price.Builder builderForValue) {
      if (limitPriceBuilder_ == null) {
        limitPrice_ = builderForValue.build();
      } else {
        limitPriceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
     */
    public Builder mergeLimitPrice(reef.contracts.orderexecution.v1.Price value) {
      if (limitPriceBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          limitPrice_ != null &&
          limitPrice_ != reef.contracts.orderexecution.v1.Price.getDefaultInstance()) {
          getLimitPriceBuilder().mergeFrom(value);
        } else {
          limitPrice_ = value;
        }
      } else {
        limitPriceBuilder_.mergeFrom(value);
      }
      if (limitPrice_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
     */
    public Builder clearLimitPrice() {
      bitField0_ = (bitField0_ & ~0x00000100);
      limitPrice_ = null;
      if (limitPriceBuilder_ != null) {
        limitPriceBuilder_.dispose();
        limitPriceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
     */
    public reef.contracts.orderexecution.v1.Price.Builder getLimitPriceBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return internalGetLimitPriceFieldBuilder().getBuilder();
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
     */
    public reef.contracts.orderexecution.v1.PriceOrBuilder getLimitPriceOrBuilder() {
      if (limitPriceBuilder_ != null) {
        return limitPriceBuilder_.getMessageOrBuilder();
      } else {
        return limitPrice_ == null ?
            reef.contracts.orderexecution.v1.Price.getDefaultInstance() : limitPrice_;
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price limit_price = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.Price, reef.contracts.orderexecution.v1.Price.Builder, reef.contracts.orderexecution.v1.PriceOrBuilder> 
        internalGetLimitPriceFieldBuilder() {
      if (limitPriceBuilder_ == null) {
        limitPriceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            reef.contracts.orderexecution.v1.Price, reef.contracts.orderexecution.v1.Price.Builder, reef.contracts.orderexecution.v1.PriceOrBuilder>(
                getLimitPrice(),
                getParentForChildren(),
                isClean());
        limitPrice_ = null;
      }
      return limitPriceBuilder_;
    }

    private int timeInForce_ = 0;
    /**
     * <code>.reef.contracts.orderexecution.v1.TimeInForce time_in_force = 10;</code>
     * @return The enum numeric value on the wire for timeInForce.
     */
    @java.lang.Override public int getTimeInForceValue() {
      return timeInForce_;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.TimeInForce time_in_force = 10;</code>
     * @param value The enum numeric value on the wire for timeInForce to set.
     * @return This builder for chaining.
     */
    public Builder setTimeInForceValue(int value) {
      timeInForce_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.TimeInForce time_in_force = 10;</code>
     * @return The timeInForce.
     */
    @java.lang.Override
    public reef.contracts.orderexecution.v1.TimeInForce getTimeInForce() {
      reef.contracts.orderexecution.v1.TimeInForce result = reef.contracts.orderexecution.v1.TimeInForce.forNumber(timeInForce_);
      return result == null ? reef.contracts.orderexecution.v1.TimeInForce.UNRECOGNIZED : result;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.TimeInForce time_in_force = 10;</code>
     * @param value The timeInForce to set.
     * @return This builder for chaining.
     */
    public Builder setTimeInForce(reef.contracts.orderexecution.v1.TimeInForce value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000200;
      timeInForce_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.TimeInForce time_in_force = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeInForce() {
      bitField0_ = (bitField0_ & ~0x00000200);
      timeInForce_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:reef.contracts.orderexecution.v1.SubmitOrder)
  }

  // @@protoc_insertion_point(class_scope:reef.contracts.orderexecution.v1.SubmitOrder)
  private static final reef.contracts.orderexecution.v1.SubmitOrder DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new reef.contracts.orderexecution.v1.SubmitOrder();
  }

  public static reef.contracts.orderexecution.v1.SubmitOrder getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubmitOrder>
      PARSER = new com.google.protobuf.AbstractParser<SubmitOrder>() {
    @java.lang.Override
    public SubmitOrder parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubmitOrder> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubmitOrder> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public reef.contracts.orderexecution.v1.SubmitOrder getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

