// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/order_execution.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.orderexecution.v1;

/**
 * Protobuf type {@code reef.contracts.orderexecution.v1.TradeCreated}
 */
@com.google.protobuf.Generated
public final class TradeCreated extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:reef.contracts.orderexecution.v1.TradeCreated)
    TradeCreatedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "TradeCreated");
  }
  // Use TradeCreated.newBuilder() to construct.
  private TradeCreated(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TradeCreated() {
    eventId_ = "";
    tradeId_ = "";
    executionId_ = "";
    buyOrderId_ = "";
    sellOrderId_ = "";
    instrumentId_ = "";
    occurredAt_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_TradeCreated_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_TradeCreated_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            reef.contracts.orderexecution.v1.TradeCreated.class, reef.contracts.orderexecution.v1.TradeCreated.Builder.class);
  }

  private int bitField0_;
  public static final int EVENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventId_ = "";
  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  @java.lang.Override
  public java.lang.String getEventId() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventId_ = s;
      return s;
    }
  }
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventIdBytes() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRADE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tradeId_ = "";
  /**
   * <code>string trade_id = 2;</code>
   * @return The tradeId.
   */
  @java.lang.Override
  public java.lang.String getTradeId() {
    java.lang.Object ref = tradeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tradeId_ = s;
      return s;
    }
  }
  /**
   * <code>string trade_id = 2;</code>
   * @return The bytes for tradeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTradeIdBytes() {
    java.lang.Object ref = tradeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tradeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXECUTION_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object executionId_ = "";
  /**
   * <code>string execution_id = 3;</code>
   * @return The executionId.
   */
  @java.lang.Override
  public java.lang.String getExecutionId() {
    java.lang.Object ref = executionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      executionId_ = s;
      return s;
    }
  }
  /**
   * <code>string execution_id = 3;</code>
   * @return The bytes for executionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExecutionIdBytes() {
    java.lang.Object ref = executionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      executionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUY_ORDER_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object buyOrderId_ = "";
  /**
   * <code>string buy_order_id = 4;</code>
   * @return The buyOrderId.
   */
  @java.lang.Override
  public java.lang.String getBuyOrderId() {
    java.lang.Object ref = buyOrderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      buyOrderId_ = s;
      return s;
    }
  }
  /**
   * <code>string buy_order_id = 4;</code>
   * @return The bytes for buyOrderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBuyOrderIdBytes() {
    java.lang.Object ref = buyOrderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buyOrderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SELL_ORDER_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sellOrderId_ = "";
  /**
   * <code>string sell_order_id = 5;</code>
   * @return The sellOrderId.
   */
  @java.lang.Override
  public java.lang.String getSellOrderId() {
    java.lang.Object ref = sellOrderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sellOrderId_ = s;
      return s;
    }
  }
  /**
   * <code>string sell_order_id = 5;</code>
   * @return The bytes for sellOrderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSellOrderIdBytes() {
    java.lang.Object ref = sellOrderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sellOrderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTRUMENT_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instrumentId_ = "";
  /**
   * <code>string instrument_id = 6;</code>
   * @return The instrumentId.
   */
  @java.lang.Override
  public java.lang.String getInstrumentId() {
    java.lang.Object ref = instrumentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instrumentId_ = s;
      return s;
    }
  }
  /**
   * <code>string instrument_id = 6;</code>
   * @return The bytes for instrumentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstrumentIdBytes() {
    java.lang.Object ref = instrumentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instrumentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 7;
  private reef.contracts.orderexecution.v1.OrderQuantity quantity_;
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
   * @return Whether the quantity field is set.
   */
  @java.lang.Override
  public boolean hasQuantity() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.OrderQuantity getQuantity() {
    return quantity_ == null ? reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance() : quantity_;
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.OrderQuantityOrBuilder getQuantityOrBuilder() {
    return quantity_ == null ? reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance() : quantity_;
  }

  public static final int PRICE_FIELD_NUMBER = 8;
  private reef.contracts.orderexecution.v1.Price price_;
  /**
   * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
   * @return Whether the price field is set.
   */
  @java.lang.Override
  public boolean hasPrice() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
   * @return The price.
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.Price getPrice() {
    return price_ == null ? reef.contracts.orderexecution.v1.Price.getDefaultInstance() : price_;
  }
  /**
   * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
   */
  @java.lang.Override
  public reef.contracts.orderexecution.v1.PriceOrBuilder getPriceOrBuilder() {
    return price_ == null ? reef.contracts.orderexecution.v1.Price.getDefaultInstance() : price_;
  }

  public static final int OCCURRED_AT_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object occurredAt_ = "";
  /**
   * <code>string occurred_at = 9;</code>
   * @return The occurredAt.
   */
  @java.lang.Override
  public java.lang.String getOccurredAt() {
    java.lang.Object ref = occurredAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      occurredAt_ = s;
      return s;
    }
  }
  /**
   * <code>string occurred_at = 9;</code>
   * @return The bytes for occurredAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOccurredAtBytes() {
    java.lang.Object ref = occurredAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      occurredAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tradeId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, tradeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(executionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, executionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(buyOrderId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, buyOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sellOrderId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, sellOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instrumentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, instrumentId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(7, getQuantity());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(8, getPrice());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(occurredAt_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, occurredAt_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tradeId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tradeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(executionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, executionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(buyOrderId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, buyOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sellOrderId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, sellOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instrumentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, instrumentId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getQuantity());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getPrice());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(occurredAt_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, occurredAt_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof reef.contracts.orderexecution.v1.TradeCreated)) {
      return super.equals(obj);
    }
    reef.contracts.orderexecution.v1.TradeCreated other = (reef.contracts.orderexecution.v1.TradeCreated) obj;

    if (!getEventId()
        .equals(other.getEventId())) return false;
    if (!getTradeId()
        .equals(other.getTradeId())) return false;
    if (!getExecutionId()
        .equals(other.getExecutionId())) return false;
    if (!getBuyOrderId()
        .equals(other.getBuyOrderId())) return false;
    if (!getSellOrderId()
        .equals(other.getSellOrderId())) return false;
    if (!getInstrumentId()
        .equals(other.getInstrumentId())) return false;
    if (hasQuantity() != other.hasQuantity()) return false;
    if (hasQuantity()) {
      if (!getQuantity()
          .equals(other.getQuantity())) return false;
    }
    if (hasPrice() != other.hasPrice()) return false;
    if (hasPrice()) {
      if (!getPrice()
          .equals(other.getPrice())) return false;
    }
    if (!getOccurredAt()
        .equals(other.getOccurredAt())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventId().hashCode();
    hash = (37 * hash) + TRADE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTradeId().hashCode();
    hash = (37 * hash) + EXECUTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getExecutionId().hashCode();
    hash = (37 * hash) + BUY_ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBuyOrderId().hashCode();
    hash = (37 * hash) + SELL_ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSellOrderId().hashCode();
    hash = (37 * hash) + INSTRUMENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInstrumentId().hashCode();
    if (hasQuantity()) {
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity().hashCode();
    }
    if (hasPrice()) {
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
    }
    hash = (37 * hash) + OCCURRED_AT_FIELD_NUMBER;
    hash = (53 * hash) + getOccurredAt().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static reef.contracts.orderexecution.v1.TradeCreated parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static reef.contracts.orderexecution.v1.TradeCreated parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.orderexecution.v1.TradeCreated parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(reef.contracts.orderexecution.v1.TradeCreated prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reef.contracts.orderexecution.v1.TradeCreated}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reef.contracts.orderexecution.v1.TradeCreated)
      reef.contracts.orderexecution.v1.TradeCreatedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_TradeCreated_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_TradeCreated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              reef.contracts.orderexecution.v1.TradeCreated.class, reef.contracts.orderexecution.v1.TradeCreated.Builder.class);
    }

    // Construct using reef.contracts.orderexecution.v1.TradeCreated.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetQuantityFieldBuilder();
        internalGetPriceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventId_ = "";
      tradeId_ = "";
      executionId_ = "";
      buyOrderId_ = "";
      sellOrderId_ = "";
      instrumentId_ = "";
      quantity_ = null;
      if (quantityBuilder_ != null) {
        quantityBuilder_.dispose();
        quantityBuilder_ = null;
      }
      price_ = null;
      if (priceBuilder_ != null) {
        priceBuilder_.dispose();
        priceBuilder_ = null;
      }
      occurredAt_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return reef.contracts.orderexecution.v1.OrderExecution.internal_static_reef_contracts_orderexecution_v1_TradeCreated_descriptor;
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.TradeCreated getDefaultInstanceForType() {
      return reef.contracts.orderexecution.v1.TradeCreated.getDefaultInstance();
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.TradeCreated build() {
      reef.contracts.orderexecution.v1.TradeCreated result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public reef.contracts.orderexecution.v1.TradeCreated buildPartial() {
      reef.contracts.orderexecution.v1.TradeCreated result = new reef.contracts.orderexecution.v1.TradeCreated(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(reef.contracts.orderexecution.v1.TradeCreated result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventId_ = eventId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tradeId_ = tradeId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.executionId_ = executionId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.buyOrderId_ = buyOrderId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sellOrderId_ = sellOrderId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.instrumentId_ = instrumentId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.quantity_ = quantityBuilder_ == null
            ? quantity_
            : quantityBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.price_ = priceBuilder_ == null
            ? price_
            : priceBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.occurredAt_ = occurredAt_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof reef.contracts.orderexecution.v1.TradeCreated) {
        return mergeFrom((reef.contracts.orderexecution.v1.TradeCreated)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(reef.contracts.orderexecution.v1.TradeCreated other) {
      if (other == reef.contracts.orderexecution.v1.TradeCreated.getDefaultInstance()) return this;
      if (!other.getEventId().isEmpty()) {
        eventId_ = other.eventId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTradeId().isEmpty()) {
        tradeId_ = other.tradeId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getExecutionId().isEmpty()) {
        executionId_ = other.executionId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getBuyOrderId().isEmpty()) {
        buyOrderId_ = other.buyOrderId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getSellOrderId().isEmpty()) {
        sellOrderId_ = other.sellOrderId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getInstrumentId().isEmpty()) {
        instrumentId_ = other.instrumentId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasQuantity()) {
        mergeQuantity(other.getQuantity());
      }
      if (other.hasPrice()) {
        mergePrice(other.getPrice());
      }
      if (!other.getOccurredAt().isEmpty()) {
        occurredAt_ = other.occurredAt_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tradeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              executionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              buyOrderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              sellOrderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              instrumentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetQuantityFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  internalGetPriceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              occurredAt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventId_ = "";
    /**
     * <code>string event_id = 1;</code>
     * @return The eventId.
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_id = 1;</code>
     * @return The bytes for eventId.
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      eventId_ = getDefaultInstance().getEventId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The bytes for eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tradeId_ = "";
    /**
     * <code>string trade_id = 2;</code>
     * @return The tradeId.
     */
    public java.lang.String getTradeId() {
      java.lang.Object ref = tradeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tradeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string trade_id = 2;</code>
     * @return The bytes for tradeId.
     */
    public com.google.protobuf.ByteString
        getTradeIdBytes() {
      java.lang.Object ref = tradeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tradeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string trade_id = 2;</code>
     * @param value The tradeId to set.
     * @return This builder for chaining.
     */
    public Builder setTradeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tradeId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string trade_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeId() {
      tradeId_ = getDefaultInstance().getTradeId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string trade_id = 2;</code>
     * @param value The bytes for tradeId to set.
     * @return This builder for chaining.
     */
    public Builder setTradeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tradeId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object executionId_ = "";
    /**
     * <code>string execution_id = 3;</code>
     * @return The executionId.
     */
    public java.lang.String getExecutionId() {
      java.lang.Object ref = executionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        executionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string execution_id = 3;</code>
     * @return The bytes for executionId.
     */
    public com.google.protobuf.ByteString
        getExecutionIdBytes() {
      java.lang.Object ref = executionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        executionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string execution_id = 3;</code>
     * @param value The executionId to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      executionId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string execution_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionId() {
      executionId_ = getDefaultInstance().getExecutionId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string execution_id = 3;</code>
     * @param value The bytes for executionId to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      executionId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object buyOrderId_ = "";
    /**
     * <code>string buy_order_id = 4;</code>
     * @return The buyOrderId.
     */
    public java.lang.String getBuyOrderId() {
      java.lang.Object ref = buyOrderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buyOrderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string buy_order_id = 4;</code>
     * @return The bytes for buyOrderId.
     */
    public com.google.protobuf.ByteString
        getBuyOrderIdBytes() {
      java.lang.Object ref = buyOrderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buyOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string buy_order_id = 4;</code>
     * @param value The buyOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setBuyOrderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      buyOrderId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string buy_order_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuyOrderId() {
      buyOrderId_ = getDefaultInstance().getBuyOrderId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string buy_order_id = 4;</code>
     * @param value The bytes for buyOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setBuyOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      buyOrderId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object sellOrderId_ = "";
    /**
     * <code>string sell_order_id = 5;</code>
     * @return The sellOrderId.
     */
    public java.lang.String getSellOrderId() {
      java.lang.Object ref = sellOrderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sellOrderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sell_order_id = 5;</code>
     * @return The bytes for sellOrderId.
     */
    public com.google.protobuf.ByteString
        getSellOrderIdBytes() {
      java.lang.Object ref = sellOrderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sellOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sell_order_id = 5;</code>
     * @param value The sellOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setSellOrderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sellOrderId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string sell_order_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSellOrderId() {
      sellOrderId_ = getDefaultInstance().getSellOrderId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string sell_order_id = 5;</code>
     * @param value The bytes for sellOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setSellOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sellOrderId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object instrumentId_ = "";
    /**
     * <code>string instrument_id = 6;</code>
     * @return The instrumentId.
     */
    public java.lang.String getInstrumentId() {
      java.lang.Object ref = instrumentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrumentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string instrument_id = 6;</code>
     * @return The bytes for instrumentId.
     */
    public com.google.protobuf.ByteString
        getInstrumentIdBytes() {
      java.lang.Object ref = instrumentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrumentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string instrument_id = 6;</code>
     * @param value The instrumentId to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instrumentId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string instrument_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstrumentId() {
      instrumentId_ = getDefaultInstance().getInstrumentId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string instrument_id = 6;</code>
     * @param value The bytes for instrumentId to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instrumentId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private reef.contracts.orderexecution.v1.OrderQuantity quantity_;
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.OrderQuantity, reef.contracts.orderexecution.v1.OrderQuantity.Builder, reef.contracts.orderexecution.v1.OrderQuantityOrBuilder> quantityBuilder_;
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
     * @return Whether the quantity field is set.
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
     * @return The quantity.
     */
    public reef.contracts.orderexecution.v1.OrderQuantity getQuantity() {
      if (quantityBuilder_ == null) {
        return quantity_ == null ? reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance() : quantity_;
      } else {
        return quantityBuilder_.getMessage();
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
     */
    public Builder setQuantity(reef.contracts.orderexecution.v1.OrderQuantity value) {
      if (quantityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        quantity_ = value;
      } else {
        quantityBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
     */
    public Builder setQuantity(
        reef.contracts.orderexecution.v1.OrderQuantity.Builder builderForValue) {
      if (quantityBuilder_ == null) {
        quantity_ = builderForValue.build();
      } else {
        quantityBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
     */
    public Builder mergeQuantity(reef.contracts.orderexecution.v1.OrderQuantity value) {
      if (quantityBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          quantity_ != null &&
          quantity_ != reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance()) {
          getQuantityBuilder().mergeFrom(value);
        } else {
          quantity_ = value;
        }
      } else {
        quantityBuilder_.mergeFrom(value);
      }
      if (quantity_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000040);
      quantity_ = null;
      if (quantityBuilder_ != null) {
        quantityBuilder_.dispose();
        quantityBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
     */
    public reef.contracts.orderexecution.v1.OrderQuantity.Builder getQuantityBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetQuantityFieldBuilder().getBuilder();
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
     */
    public reef.contracts.orderexecution.v1.OrderQuantityOrBuilder getQuantityOrBuilder() {
      if (quantityBuilder_ != null) {
        return quantityBuilder_.getMessageOrBuilder();
      } else {
        return quantity_ == null ?
            reef.contracts.orderexecution.v1.OrderQuantity.getDefaultInstance() : quantity_;
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.OrderQuantity quantity = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.OrderQuantity, reef.contracts.orderexecution.v1.OrderQuantity.Builder, reef.contracts.orderexecution.v1.OrderQuantityOrBuilder> 
        internalGetQuantityFieldBuilder() {
      if (quantityBuilder_ == null) {
        quantityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            reef.contracts.orderexecution.v1.OrderQuantity, reef.contracts.orderexecution.v1.OrderQuantity.Builder, reef.contracts.orderexecution.v1.OrderQuantityOrBuilder>(
                getQuantity(),
                getParentForChildren(),
                isClean());
        quantity_ = null;
      }
      return quantityBuilder_;
    }

    private reef.contracts.orderexecution.v1.Price price_;
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.Price, reef.contracts.orderexecution.v1.Price.Builder, reef.contracts.orderexecution.v1.PriceOrBuilder> priceBuilder_;
    /**
     * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
     * @return Whether the price field is set.
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
     * @return The price.
     */
    public reef.contracts.orderexecution.v1.Price getPrice() {
      if (priceBuilder_ == null) {
        return price_ == null ? reef.contracts.orderexecution.v1.Price.getDefaultInstance() : price_;
      } else {
        return priceBuilder_.getMessage();
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
     */
    public Builder setPrice(reef.contracts.orderexecution.v1.Price value) {
      if (priceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        price_ = value;
      } else {
        priceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
     */
    public Builder setPrice(
        reef.contracts.orderexecution.v1.Price.Builder builderForValue) {
      if (priceBuilder_ == null) {
        price_ = builderForValue.build();
      } else {
        priceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
     */
    public Builder mergePrice(reef.contracts.orderexecution.v1.Price value) {
      if (priceBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          price_ != null &&
          price_ != reef.contracts.orderexecution.v1.Price.getDefaultInstance()) {
          getPriceBuilder().mergeFrom(value);
        } else {
          price_ = value;
        }
      } else {
        priceBuilder_.mergeFrom(value);
      }
      if (price_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000080);
      price_ = null;
      if (priceBuilder_ != null) {
        priceBuilder_.dispose();
        priceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
     */
    public reef.contracts.orderexecution.v1.Price.Builder getPriceBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return internalGetPriceFieldBuilder().getBuilder();
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
     */
    public reef.contracts.orderexecution.v1.PriceOrBuilder getPriceOrBuilder() {
      if (priceBuilder_ != null) {
        return priceBuilder_.getMessageOrBuilder();
      } else {
        return price_ == null ?
            reef.contracts.orderexecution.v1.Price.getDefaultInstance() : price_;
      }
    }
    /**
     * <code>.reef.contracts.orderexecution.v1.Price price = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.orderexecution.v1.Price, reef.contracts.orderexecution.v1.Price.Builder, reef.contracts.orderexecution.v1.PriceOrBuilder> 
        internalGetPriceFieldBuilder() {
      if (priceBuilder_ == null) {
        priceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            reef.contracts.orderexecution.v1.Price, reef.contracts.orderexecution.v1.Price.Builder, reef.contracts.orderexecution.v1.PriceOrBuilder>(
                getPrice(),
                getParentForChildren(),
                isClean());
        price_ = null;
      }
      return priceBuilder_;
    }

    private java.lang.Object occurredAt_ = "";
    /**
     * <code>string occurred_at = 9;</code>
     * @return The occurredAt.
     */
    public java.lang.String getOccurredAt() {
      java.lang.Object ref = occurredAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        occurredAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string occurred_at = 9;</code>
     * @return The bytes for occurredAt.
     */
    public com.google.protobuf.ByteString
        getOccurredAtBytes() {
      java.lang.Object ref = occurredAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        occurredAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string occurred_at = 9;</code>
     * @param value The occurredAt to set.
     * @return This builder for chaining.
     */
    public Builder setOccurredAt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      occurredAt_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string occurred_at = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearOccurredAt() {
      occurredAt_ = getDefaultInstance().getOccurredAt();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string occurred_at = 9;</code>
     * @param value The bytes for occurredAt to set.
     * @return This builder for chaining.
     */
    public Builder setOccurredAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      occurredAt_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:reef.contracts.orderexecution.v1.TradeCreated)
  }

  // @@protoc_insertion_point(class_scope:reef.contracts.orderexecution.v1.TradeCreated)
  private static final reef.contracts.orderexecution.v1.TradeCreated DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new reef.contracts.orderexecution.v1.TradeCreated();
  }

  public static reef.contracts.orderexecution.v1.TradeCreated getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TradeCreated>
      PARSER = new com.google.protobuf.AbstractParser<TradeCreated>() {
    @java.lang.Override
    public TradeCreated parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TradeCreated> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TradeCreated> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public reef.contracts.orderexecution.v1.TradeCreated getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

