// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

/**
 * Protobuf type {@code reef.contracts.calcify.v1.CommitmentSourceV1}
 */
@com.google.protobuf.Generated
public final class CommitmentSourceV1 extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:reef.contracts.calcify.v1.CommitmentSourceV1)
    CommitmentSourceV1OrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "CommitmentSourceV1");
  }
  // Use CommitmentSourceV1.newBuilder() to construct.
  private CommitmentSourceV1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CommitmentSourceV1() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_CommitmentSourceV1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_CommitmentSourceV1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            reef.contracts.calcify.v1.CommitmentSourceV1.class, reef.contracts.calcify.v1.CommitmentSourceV1.Builder.class);
  }

  public static final int SOURCE_GENERATION_FIELD_NUMBER = 1;
  private int sourceGeneration_ = 0;
  /**
   * <code>uint32 source_generation = 1;</code>
   * @return The sourceGeneration.
   */
  @java.lang.Override
  public int getSourceGeneration() {
    return sourceGeneration_;
  }

  public static final int SOURCE_PARTITION_FIELD_NUMBER = 2;
  private int sourcePartition_ = 0;
  /**
   * <code>uint32 source_partition = 2;</code>
   * @return The sourcePartition.
   */
  @java.lang.Override
  public int getSourcePartition() {
    return sourcePartition_;
  }

  public static final int SOURCE_OFFSET_FIELD_NUMBER = 3;
  private long sourceOffset_ = 0L;
  /**
   * <code>int64 source_offset = 3;</code>
   * @return The sourceOffset.
   */
  @java.lang.Override
  public long getSourceOffset() {
    return sourceOffset_;
  }

  public static final int TRADE_ORDINAL_FIELD_NUMBER = 4;
  private int tradeOrdinal_ = 0;
  /**
   * <code>uint32 trade_ordinal = 4;</code>
   * @return The tradeOrdinal.
   */
  @java.lang.Override
  public int getTradeOrdinal() {
    return tradeOrdinal_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sourceGeneration_ != 0) {
      output.writeUInt32(1, sourceGeneration_);
    }
    if (sourcePartition_ != 0) {
      output.writeUInt32(2, sourcePartition_);
    }
    if (sourceOffset_ != 0L) {
      output.writeInt64(3, sourceOffset_);
    }
    if (tradeOrdinal_ != 0) {
      output.writeUInt32(4, tradeOrdinal_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sourceGeneration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, sourceGeneration_);
    }
    if (sourcePartition_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, sourcePartition_);
    }
    if (sourceOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, sourceOffset_);
    }
    if (tradeOrdinal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, tradeOrdinal_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof reef.contracts.calcify.v1.CommitmentSourceV1)) {
      return super.equals(obj);
    }
    reef.contracts.calcify.v1.CommitmentSourceV1 other = (reef.contracts.calcify.v1.CommitmentSourceV1) obj;

    if (getSourceGeneration()
        != other.getSourceGeneration()) return false;
    if (getSourcePartition()
        != other.getSourcePartition()) return false;
    if (getSourceOffset()
        != other.getSourceOffset()) return false;
    if (getTradeOrdinal()
        != other.getTradeOrdinal()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCE_GENERATION_FIELD_NUMBER;
    hash = (53 * hash) + getSourceGeneration();
    hash = (37 * hash) + SOURCE_PARTITION_FIELD_NUMBER;
    hash = (53 * hash) + getSourcePartition();
    hash = (37 * hash) + SOURCE_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSourceOffset());
    hash = (37 * hash) + TRADE_ORDINAL_FIELD_NUMBER;
    hash = (53 * hash) + getTradeOrdinal();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.calcify.v1.CommitmentSourceV1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(reef.contracts.calcify.v1.CommitmentSourceV1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reef.contracts.calcify.v1.CommitmentSourceV1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reef.contracts.calcify.v1.CommitmentSourceV1)
      reef.contracts.calcify.v1.CommitmentSourceV1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_CommitmentSourceV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_CommitmentSourceV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              reef.contracts.calcify.v1.CommitmentSourceV1.class, reef.contracts.calcify.v1.CommitmentSourceV1.Builder.class);
    }

    // Construct using reef.contracts.calcify.v1.CommitmentSourceV1.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sourceGeneration_ = 0;
      sourcePartition_ = 0;
      sourceOffset_ = 0L;
      tradeOrdinal_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_CommitmentSourceV1_descriptor;
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.CommitmentSourceV1 getDefaultInstanceForType() {
      return reef.contracts.calcify.v1.CommitmentSourceV1.getDefaultInstance();
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.CommitmentSourceV1 build() {
      reef.contracts.calcify.v1.CommitmentSourceV1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.CommitmentSourceV1 buildPartial() {
      reef.contracts.calcify.v1.CommitmentSourceV1 result = new reef.contracts.calcify.v1.CommitmentSourceV1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(reef.contracts.calcify.v1.CommitmentSourceV1 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sourceGeneration_ = sourceGeneration_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sourcePartition_ = sourcePartition_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sourceOffset_ = sourceOffset_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tradeOrdinal_ = tradeOrdinal_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof reef.contracts.calcify.v1.CommitmentSourceV1) {
        return mergeFrom((reef.contracts.calcify.v1.CommitmentSourceV1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(reef.contracts.calcify.v1.CommitmentSourceV1 other) {
      if (other == reef.contracts.calcify.v1.CommitmentSourceV1.getDefaultInstance()) return this;
      if (other.getSourceGeneration() != 0) {
        setSourceGeneration(other.getSourceGeneration());
      }
      if (other.getSourcePartition() != 0) {
        setSourcePartition(other.getSourcePartition());
      }
      if (other.getSourceOffset() != 0L) {
        setSourceOffset(other.getSourceOffset());
      }
      if (other.getTradeOrdinal() != 0) {
        setTradeOrdinal(other.getTradeOrdinal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sourceGeneration_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              sourcePartition_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              sourceOffset_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              tradeOrdinal_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int sourceGeneration_ ;
    /**
     * <code>uint32 source_generation = 1;</code>
     * @return The sourceGeneration.
     */
    @java.lang.Override
    public int getSourceGeneration() {
      return sourceGeneration_;
    }
    /**
     * <code>uint32 source_generation = 1;</code>
     * @param value The sourceGeneration to set.
     * @return This builder for chaining.
     */
    public Builder setSourceGeneration(int value) {

      sourceGeneration_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 source_generation = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceGeneration() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sourceGeneration_ = 0;
      onChanged();
      return this;
    }

    private int sourcePartition_ ;
    /**
     * <code>uint32 source_partition = 2;</code>
     * @return The sourcePartition.
     */
    @java.lang.Override
    public int getSourcePartition() {
      return sourcePartition_;
    }
    /**
     * <code>uint32 source_partition = 2;</code>
     * @param value The sourcePartition to set.
     * @return This builder for chaining.
     */
    public Builder setSourcePartition(int value) {

      sourcePartition_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 source_partition = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourcePartition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sourcePartition_ = 0;
      onChanged();
      return this;
    }

    private long sourceOffset_ ;
    /**
     * <code>int64 source_offset = 3;</code>
     * @return The sourceOffset.
     */
    @java.lang.Override
    public long getSourceOffset() {
      return sourceOffset_;
    }
    /**
     * <code>int64 source_offset = 3;</code>
     * @param value The sourceOffset to set.
     * @return This builder for chaining.
     */
    public Builder setSourceOffset(long value) {

      sourceOffset_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 source_offset = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceOffset() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sourceOffset_ = 0L;
      onChanged();
      return this;
    }

    private int tradeOrdinal_ ;
    /**
     * <code>uint32 trade_ordinal = 4;</code>
     * @return The tradeOrdinal.
     */
    @java.lang.Override
    public int getTradeOrdinal() {
      return tradeOrdinal_;
    }
    /**
     * <code>uint32 trade_ordinal = 4;</code>
     * @param value The tradeOrdinal to set.
     * @return This builder for chaining.
     */
    public Builder setTradeOrdinal(int value) {

      tradeOrdinal_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 trade_ordinal = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeOrdinal() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tradeOrdinal_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:reef.contracts.calcify.v1.CommitmentSourceV1)
  }

  // @@protoc_insertion_point(class_scope:reef.contracts.calcify.v1.CommitmentSourceV1)
  private static final reef.contracts.calcify.v1.CommitmentSourceV1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new reef.contracts.calcify.v1.CommitmentSourceV1();
  }

  public static reef.contracts.calcify.v1.CommitmentSourceV1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommitmentSourceV1>
      PARSER = new com.google.protobuf.AbstractParser<CommitmentSourceV1>() {
    @java.lang.Override
    public CommitmentSourceV1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CommitmentSourceV1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommitmentSourceV1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public reef.contracts.calcify.v1.CommitmentSourceV1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
