// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

/**
 * Protobuf type {@code reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1}
 */
@com.google.protobuf.Generated
public final class FiniteLifecycleOrderStateV1 extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1)
    FiniteLifecycleOrderStateV1OrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "FiniteLifecycleOrderStateV1");
  }
  // Use FiniteLifecycleOrderStateV1.newBuilder() to construct.
  private FiniteLifecycleOrderStateV1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FiniteLifecycleOrderStateV1() {
    quantityUnits_ = "";
    limitPrice_ = "";
    filledUnits_ = "";
    terminal_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleOrderStateV1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleOrderStateV1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1.class, reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1.Builder.class);
  }

  private int bitField0_;
  public static final int ACCEPTANCE_FIELD_NUMBER = 1;
  private reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance_;
  /**
   * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
   * @return Whether the acceptance field is set.
   */
  @java.lang.Override
  public boolean hasAcceptance() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
   * @return The acceptance.
   */
  @java.lang.Override
  public reef.contracts.calcify.v1.AcceptedOrderSourceV1 getAcceptance() {
    return acceptance_ == null ? reef.contracts.calcify.v1.AcceptedOrderSourceV1.getDefaultInstance() : acceptance_;
  }
  /**
   * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
   */
  @java.lang.Override
  public reef.contracts.calcify.v1.AcceptedOrderSourceV1OrBuilder getAcceptanceOrBuilder() {
    return acceptance_ == null ? reef.contracts.calcify.v1.AcceptedOrderSourceV1.getDefaultInstance() : acceptance_;
  }

  public static final int REVISION_FIELD_NUMBER = 2;
  private reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision_;
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
   * @return Whether the revision field is set.
   */
  @java.lang.Override
  public boolean hasRevision() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
   * @return The revision.
   */
  @java.lang.Override
  public reef.contracts.calcify.v1.LifecycleRevisionIdV1 getRevision() {
    return revision_ == null ? reef.contracts.calcify.v1.LifecycleRevisionIdV1.getDefaultInstance() : revision_;
  }
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
   */
  @java.lang.Override
  public reef.contracts.calcify.v1.LifecycleRevisionIdV1OrBuilder getRevisionOrBuilder() {
    return revision_ == null ? reef.contracts.calcify.v1.LifecycleRevisionIdV1.getDefaultInstance() : revision_;
  }

  public static final int PREVIOUS_EFFECT_FIELD_NUMBER = 3;
  private reef.contracts.calcify.v1.LifecycleMemberIdV1 previousEffect_;
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
   * @return Whether the previousEffect field is set.
   */
  @java.lang.Override
  public boolean hasPreviousEffect() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
   * @return The previousEffect.
   */
  @java.lang.Override
  public reef.contracts.calcify.v1.LifecycleMemberIdV1 getPreviousEffect() {
    return previousEffect_ == null ? reef.contracts.calcify.v1.LifecycleMemberIdV1.getDefaultInstance() : previousEffect_;
  }
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
   */
  @java.lang.Override
  public reef.contracts.calcify.v1.LifecycleMemberIdV1OrBuilder getPreviousEffectOrBuilder() {
    return previousEffect_ == null ? reef.contracts.calcify.v1.LifecycleMemberIdV1.getDefaultInstance() : previousEffect_;
  }

  public static final int QUANTITY_UNITS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object quantityUnits_ = "";
  /**
   * <code>string quantity_units = 4;</code>
   * @return The quantityUnits.
   */
  @java.lang.Override
  public java.lang.String getQuantityUnits() {
    java.lang.Object ref = quantityUnits_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quantityUnits_ = s;
      return s;
    }
  }
  /**
   * <code>string quantity_units = 4;</code>
   * @return The bytes for quantityUnits.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuantityUnitsBytes() {
    java.lang.Object ref = quantityUnits_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quantityUnits_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIMIT_PRICE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object limitPrice_ = "";
  /**
   * <code>string limit_price = 5;</code>
   * @return The limitPrice.
   */
  @java.lang.Override
  public java.lang.String getLimitPrice() {
    java.lang.Object ref = limitPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      limitPrice_ = s;
      return s;
    }
  }
  /**
   * <code>string limit_price = 5;</code>
   * @return The bytes for limitPrice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLimitPriceBytes() {
    java.lang.Object ref = limitPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      limitPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILLED_UNITS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object filledUnits_ = "";
  /**
   * <code>string filled_units = 6;</code>
   * @return The filledUnits.
   */
  @java.lang.Override
  public java.lang.String getFilledUnits() {
    java.lang.Object ref = filledUnits_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filledUnits_ = s;
      return s;
    }
  }
  /**
   * <code>string filled_units = 6;</code>
   * @return The bytes for filledUnits.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilledUnitsBytes() {
    java.lang.Object ref = filledUnits_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filledUnits_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERMINAL_FIELD_NUMBER = 7;
  private int terminal_ = 0;
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleOrderTerminalV1 terminal = 7;</code>
   * @return The enum numeric value on the wire for terminal.
   */
  @java.lang.Override public int getTerminalValue() {
    return terminal_;
  }
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleOrderTerminalV1 terminal = 7;</code>
   * @return The terminal.
   */
  @java.lang.Override public reef.contracts.calcify.v1.LifecycleOrderTerminalV1 getTerminal() {
    reef.contracts.calcify.v1.LifecycleOrderTerminalV1 result = reef.contracts.calcify.v1.LifecycleOrderTerminalV1.forNumber(terminal_);
    return result == null ? reef.contracts.calcify.v1.LifecycleOrderTerminalV1.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getAcceptance());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getRevision());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getPreviousEffect());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantityUnits_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, quantityUnits_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(limitPrice_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, limitPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filledUnits_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, filledUnits_);
    }
    if (terminal_ != reef.contracts.calcify.v1.LifecycleOrderTerminalV1.LIFECYCLE_ORDER_OPEN.getNumber()) {
      output.writeEnum(7, terminal_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAcceptance());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRevision());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPreviousEffect());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quantityUnits_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, quantityUnits_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(limitPrice_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, limitPrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(filledUnits_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, filledUnits_);
    }
    if (terminal_ != reef.contracts.calcify.v1.LifecycleOrderTerminalV1.LIFECYCLE_ORDER_OPEN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, terminal_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1)) {
      return super.equals(obj);
    }
    reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 other = (reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1) obj;

    if (hasAcceptance() != other.hasAcceptance()) return false;
    if (hasAcceptance()) {
      if (!getAcceptance()
          .equals(other.getAcceptance())) return false;
    }
    if (hasRevision() != other.hasRevision()) return false;
    if (hasRevision()) {
      if (!getRevision()
          .equals(other.getRevision())) return false;
    }
    if (hasPreviousEffect() != other.hasPreviousEffect()) return false;
    if (hasPreviousEffect()) {
      if (!getPreviousEffect()
          .equals(other.getPreviousEffect())) return false;
    }
    if (!getQuantityUnits()
        .equals(other.getQuantityUnits())) return false;
    if (!getLimitPrice()
        .equals(other.getLimitPrice())) return false;
    if (!getFilledUnits()
        .equals(other.getFilledUnits())) return false;
    if (terminal_ != other.terminal_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAcceptance()) {
      hash = (37 * hash) + ACCEPTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getAcceptance().hashCode();
    }
    if (hasRevision()) {
      hash = (37 * hash) + REVISION_FIELD_NUMBER;
      hash = (53 * hash) + getRevision().hashCode();
    }
    if (hasPreviousEffect()) {
      hash = (37 * hash) + PREVIOUS_EFFECT_FIELD_NUMBER;
      hash = (53 * hash) + getPreviousEffect().hashCode();
    }
    hash = (37 * hash) + QUANTITY_UNITS_FIELD_NUMBER;
    hash = (53 * hash) + getQuantityUnits().hashCode();
    hash = (37 * hash) + LIMIT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getLimitPrice().hashCode();
    hash = (37 * hash) + FILLED_UNITS_FIELD_NUMBER;
    hash = (53 * hash) + getFilledUnits().hashCode();
    hash = (37 * hash) + TERMINAL_FIELD_NUMBER;
    hash = (53 * hash) + terminal_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1)
      reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleOrderStateV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleOrderStateV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1.class, reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1.Builder.class);
    }

    // Construct using reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetAcceptanceFieldBuilder();
        internalGetRevisionFieldBuilder();
        internalGetPreviousEffectFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      acceptance_ = null;
      if (acceptanceBuilder_ != null) {
        acceptanceBuilder_.dispose();
        acceptanceBuilder_ = null;
      }
      revision_ = null;
      if (revisionBuilder_ != null) {
        revisionBuilder_.dispose();
        revisionBuilder_ = null;
      }
      previousEffect_ = null;
      if (previousEffectBuilder_ != null) {
        previousEffectBuilder_.dispose();
        previousEffectBuilder_ = null;
      }
      quantityUnits_ = "";
      limitPrice_ = "";
      filledUnits_ = "";
      terminal_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleOrderStateV1_descriptor;
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 getDefaultInstanceForType() {
      return reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1.getDefaultInstance();
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 build() {
      reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 buildPartial() {
      reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 result = new reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.acceptance_ = acceptanceBuilder_ == null
            ? acceptance_
            : acceptanceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.revision_ = revisionBuilder_ == null
            ? revision_
            : revisionBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.previousEffect_ = previousEffectBuilder_ == null
            ? previousEffect_
            : previousEffectBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.quantityUnits_ = quantityUnits_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.limitPrice_ = limitPrice_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.filledUnits_ = filledUnits_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.terminal_ = terminal_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1) {
        return mergeFrom((reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 other) {
      if (other == reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1.getDefaultInstance()) return this;
      if (other.hasAcceptance()) {
        mergeAcceptance(other.getAcceptance());
      }
      if (other.hasRevision()) {
        mergeRevision(other.getRevision());
      }
      if (other.hasPreviousEffect()) {
        mergePreviousEffect(other.getPreviousEffect());
      }
      if (!other.getQuantityUnits().isEmpty()) {
        quantityUnits_ = other.quantityUnits_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getLimitPrice().isEmpty()) {
        limitPrice_ = other.limitPrice_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getFilledUnits().isEmpty()) {
        filledUnits_ = other.filledUnits_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.terminal_ != 0) {
        setTerminalValue(other.getTerminalValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetAcceptanceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRevisionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetPreviousEffectFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              quantityUnits_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              limitPrice_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              filledUnits_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              terminal_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance_;
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.calcify.v1.AcceptedOrderSourceV1, reef.contracts.calcify.v1.AcceptedOrderSourceV1.Builder, reef.contracts.calcify.v1.AcceptedOrderSourceV1OrBuilder> acceptanceBuilder_;
    /**
     * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
     * @return Whether the acceptance field is set.
     */
    public boolean hasAcceptance() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
     * @return The acceptance.
     */
    public reef.contracts.calcify.v1.AcceptedOrderSourceV1 getAcceptance() {
      if (acceptanceBuilder_ == null) {
        return acceptance_ == null ? reef.contracts.calcify.v1.AcceptedOrderSourceV1.getDefaultInstance() : acceptance_;
      } else {
        return acceptanceBuilder_.getMessage();
      }
    }
    /**
     * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
     */
    public Builder setAcceptance(reef.contracts.calcify.v1.AcceptedOrderSourceV1 value) {
      if (acceptanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        acceptance_ = value;
      } else {
        acceptanceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
     */
    public Builder setAcceptance(
        reef.contracts.calcify.v1.AcceptedOrderSourceV1.Builder builderForValue) {
      if (acceptanceBuilder_ == null) {
        acceptance_ = builderForValue.build();
      } else {
        acceptanceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
     */
    public Builder mergeAcceptance(reef.contracts.calcify.v1.AcceptedOrderSourceV1 value) {
      if (acceptanceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          acceptance_ != null &&
          acceptance_ != reef.contracts.calcify.v1.AcceptedOrderSourceV1.getDefaultInstance()) {
          getAcceptanceBuilder().mergeFrom(value);
        } else {
          acceptance_ = value;
        }
      } else {
        acceptanceBuilder_.mergeFrom(value);
      }
      if (acceptance_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
     */
    public Builder clearAcceptance() {
      bitField0_ = (bitField0_ & ~0x00000001);
      acceptance_ = null;
      if (acceptanceBuilder_ != null) {
        acceptanceBuilder_.dispose();
        acceptanceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
     */
    public reef.contracts.calcify.v1.AcceptedOrderSourceV1.Builder getAcceptanceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetAcceptanceFieldBuilder().getBuilder();
    }
    /**
     * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
     */
    public reef.contracts.calcify.v1.AcceptedOrderSourceV1OrBuilder getAcceptanceOrBuilder() {
      if (acceptanceBuilder_ != null) {
        return acceptanceBuilder_.getMessageOrBuilder();
      } else {
        return acceptance_ == null ?
            reef.contracts.calcify.v1.AcceptedOrderSourceV1.getDefaultInstance() : acceptance_;
      }
    }
    /**
     * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 acceptance = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.calcify.v1.AcceptedOrderSourceV1, reef.contracts.calcify.v1.AcceptedOrderSourceV1.Builder, reef.contracts.calcify.v1.AcceptedOrderSourceV1OrBuilder>
        internalGetAcceptanceFieldBuilder() {
      if (acceptanceBuilder_ == null) {
        acceptanceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            reef.contracts.calcify.v1.AcceptedOrderSourceV1, reef.contracts.calcify.v1.AcceptedOrderSourceV1.Builder, reef.contracts.calcify.v1.AcceptedOrderSourceV1OrBuilder>(
                getAcceptance(),
                getParentForChildren(),
                isClean());
        acceptance_ = null;
      }
      return acceptanceBuilder_;
    }

    private reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision_;
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.calcify.v1.LifecycleRevisionIdV1, reef.contracts.calcify.v1.LifecycleRevisionIdV1.Builder, reef.contracts.calcify.v1.LifecycleRevisionIdV1OrBuilder> revisionBuilder_;
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
     * @return Whether the revision field is set.
     */
    public boolean hasRevision() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
     * @return The revision.
     */
    public reef.contracts.calcify.v1.LifecycleRevisionIdV1 getRevision() {
      if (revisionBuilder_ == null) {
        return revision_ == null ? reef.contracts.calcify.v1.LifecycleRevisionIdV1.getDefaultInstance() : revision_;
      } else {
        return revisionBuilder_.getMessage();
      }
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
     */
    public Builder setRevision(reef.contracts.calcify.v1.LifecycleRevisionIdV1 value) {
      if (revisionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        revision_ = value;
      } else {
        revisionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
     */
    public Builder setRevision(
        reef.contracts.calcify.v1.LifecycleRevisionIdV1.Builder builderForValue) {
      if (revisionBuilder_ == null) {
        revision_ = builderForValue.build();
      } else {
        revisionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
     */
    public Builder mergeRevision(reef.contracts.calcify.v1.LifecycleRevisionIdV1 value) {
      if (revisionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          revision_ != null &&
          revision_ != reef.contracts.calcify.v1.LifecycleRevisionIdV1.getDefaultInstance()) {
          getRevisionBuilder().mergeFrom(value);
        } else {
          revision_ = value;
        }
      } else {
        revisionBuilder_.mergeFrom(value);
      }
      if (revision_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
     */
    public Builder clearRevision() {
      bitField0_ = (bitField0_ & ~0x00000002);
      revision_ = null;
      if (revisionBuilder_ != null) {
        revisionBuilder_.dispose();
        revisionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
     */
    public reef.contracts.calcify.v1.LifecycleRevisionIdV1.Builder getRevisionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetRevisionFieldBuilder().getBuilder();
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
     */
    public reef.contracts.calcify.v1.LifecycleRevisionIdV1OrBuilder getRevisionOrBuilder() {
      if (revisionBuilder_ != null) {
        return revisionBuilder_.getMessageOrBuilder();
      } else {
        return revision_ == null ?
            reef.contracts.calcify.v1.LifecycleRevisionIdV1.getDefaultInstance() : revision_;
      }
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 revision = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.calcify.v1.LifecycleRevisionIdV1, reef.contracts.calcify.v1.LifecycleRevisionIdV1.Builder, reef.contracts.calcify.v1.LifecycleRevisionIdV1OrBuilder>
        internalGetRevisionFieldBuilder() {
      if (revisionBuilder_ == null) {
        revisionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            reef.contracts.calcify.v1.LifecycleRevisionIdV1, reef.contracts.calcify.v1.LifecycleRevisionIdV1.Builder, reef.contracts.calcify.v1.LifecycleRevisionIdV1OrBuilder>(
                getRevision(),
                getParentForChildren(),
                isClean());
        revision_ = null;
      }
      return revisionBuilder_;
    }

    private reef.contracts.calcify.v1.LifecycleMemberIdV1 previousEffect_;
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.calcify.v1.LifecycleMemberIdV1, reef.contracts.calcify.v1.LifecycleMemberIdV1.Builder, reef.contracts.calcify.v1.LifecycleMemberIdV1OrBuilder> previousEffectBuilder_;
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
     * @return Whether the previousEffect field is set.
     */
    public boolean hasPreviousEffect() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
     * @return The previousEffect.
     */
    public reef.contracts.calcify.v1.LifecycleMemberIdV1 getPreviousEffect() {
      if (previousEffectBuilder_ == null) {
        return previousEffect_ == null ? reef.contracts.calcify.v1.LifecycleMemberIdV1.getDefaultInstance() : previousEffect_;
      } else {
        return previousEffectBuilder_.getMessage();
      }
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
     */
    public Builder setPreviousEffect(reef.contracts.calcify.v1.LifecycleMemberIdV1 value) {
      if (previousEffectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        previousEffect_ = value;
      } else {
        previousEffectBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
     */
    public Builder setPreviousEffect(
        reef.contracts.calcify.v1.LifecycleMemberIdV1.Builder builderForValue) {
      if (previousEffectBuilder_ == null) {
        previousEffect_ = builderForValue.build();
      } else {
        previousEffectBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
     */
    public Builder mergePreviousEffect(reef.contracts.calcify.v1.LifecycleMemberIdV1 value) {
      if (previousEffectBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          previousEffect_ != null &&
          previousEffect_ != reef.contracts.calcify.v1.LifecycleMemberIdV1.getDefaultInstance()) {
          getPreviousEffectBuilder().mergeFrom(value);
        } else {
          previousEffect_ = value;
        }
      } else {
        previousEffectBuilder_.mergeFrom(value);
      }
      if (previousEffect_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
     */
    public Builder clearPreviousEffect() {
      bitField0_ = (bitField0_ & ~0x00000004);
      previousEffect_ = null;
      if (previousEffectBuilder_ != null) {
        previousEffectBuilder_.dispose();
        previousEffectBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
     */
    public reef.contracts.calcify.v1.LifecycleMemberIdV1.Builder getPreviousEffectBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetPreviousEffectFieldBuilder().getBuilder();
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
     */
    public reef.contracts.calcify.v1.LifecycleMemberIdV1OrBuilder getPreviousEffectOrBuilder() {
      if (previousEffectBuilder_ != null) {
        return previousEffectBuilder_.getMessageOrBuilder();
      } else {
        return previousEffect_ == null ?
            reef.contracts.calcify.v1.LifecycleMemberIdV1.getDefaultInstance() : previousEffect_;
      }
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 previous_effect = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.calcify.v1.LifecycleMemberIdV1, reef.contracts.calcify.v1.LifecycleMemberIdV1.Builder, reef.contracts.calcify.v1.LifecycleMemberIdV1OrBuilder>
        internalGetPreviousEffectFieldBuilder() {
      if (previousEffectBuilder_ == null) {
        previousEffectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            reef.contracts.calcify.v1.LifecycleMemberIdV1, reef.contracts.calcify.v1.LifecycleMemberIdV1.Builder, reef.contracts.calcify.v1.LifecycleMemberIdV1OrBuilder>(
                getPreviousEffect(),
                getParentForChildren(),
                isClean());
        previousEffect_ = null;
      }
      return previousEffectBuilder_;
    }

    private java.lang.Object quantityUnits_ = "";
    /**
     * <code>string quantity_units = 4;</code>
     * @return The quantityUnits.
     */
    public java.lang.String getQuantityUnits() {
      java.lang.Object ref = quantityUnits_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quantityUnits_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string quantity_units = 4;</code>
     * @return The bytes for quantityUnits.
     */
    public com.google.protobuf.ByteString
        getQuantityUnitsBytes() {
      java.lang.Object ref = quantityUnits_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quantityUnits_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string quantity_units = 4;</code>
     * @param value The quantityUnits to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityUnits(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      quantityUnits_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string quantity_units = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantityUnits() {
      quantityUnits_ = getDefaultInstance().getQuantityUnits();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string quantity_units = 4;</code>
     * @param value The bytes for quantityUnits to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityUnitsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quantityUnits_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object limitPrice_ = "";
    /**
     * <code>string limit_price = 5;</code>
     * @return The limitPrice.
     */
    public java.lang.String getLimitPrice() {
      java.lang.Object ref = limitPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        limitPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string limit_price = 5;</code>
     * @return The bytes for limitPrice.
     */
    public com.google.protobuf.ByteString
        getLimitPriceBytes() {
      java.lang.Object ref = limitPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        limitPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string limit_price = 5;</code>
     * @param value The limitPrice to set.
     * @return This builder for chaining.
     */
    public Builder setLimitPrice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      limitPrice_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string limit_price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimitPrice() {
      limitPrice_ = getDefaultInstance().getLimitPrice();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string limit_price = 5;</code>
     * @param value The bytes for limitPrice to set.
     * @return This builder for chaining.
     */
    public Builder setLimitPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      limitPrice_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object filledUnits_ = "";
    /**
     * <code>string filled_units = 6;</code>
     * @return The filledUnits.
     */
    public java.lang.String getFilledUnits() {
      java.lang.Object ref = filledUnits_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filledUnits_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filled_units = 6;</code>
     * @return The bytes for filledUnits.
     */
    public com.google.protobuf.ByteString
        getFilledUnitsBytes() {
      java.lang.Object ref = filledUnits_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filledUnits_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filled_units = 6;</code>
     * @param value The filledUnits to set.
     * @return This builder for chaining.
     */
    public Builder setFilledUnits(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      filledUnits_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string filled_units = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilledUnits() {
      filledUnits_ = getDefaultInstance().getFilledUnits();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string filled_units = 6;</code>
     * @param value The bytes for filledUnits to set.
     * @return This builder for chaining.
     */
    public Builder setFilledUnitsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      filledUnits_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int terminal_ = 0;
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleOrderTerminalV1 terminal = 7;</code>
     * @return The enum numeric value on the wire for terminal.
     */
    @java.lang.Override public int getTerminalValue() {
      return terminal_;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleOrderTerminalV1 terminal = 7;</code>
     * @param value The enum numeric value on the wire for terminal to set.
     * @return This builder for chaining.
     */
    public Builder setTerminalValue(int value) {
      terminal_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleOrderTerminalV1 terminal = 7;</code>
     * @return The terminal.
     */
    @java.lang.Override
    public reef.contracts.calcify.v1.LifecycleOrderTerminalV1 getTerminal() {
      reef.contracts.calcify.v1.LifecycleOrderTerminalV1 result = reef.contracts.calcify.v1.LifecycleOrderTerminalV1.forNumber(terminal_);
      return result == null ? reef.contracts.calcify.v1.LifecycleOrderTerminalV1.UNRECOGNIZED : result;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleOrderTerminalV1 terminal = 7;</code>
     * @param value The terminal to set.
     * @return This builder for chaining.
     */
    public Builder setTerminal(reef.contracts.calcify.v1.LifecycleOrderTerminalV1 value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000040;
      terminal_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.LifecycleOrderTerminalV1 terminal = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerminal() {
      bitField0_ = (bitField0_ & ~0x00000040);
      terminal_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1)
  }

  // @@protoc_insertion_point(class_scope:reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1)
  private static final reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1();
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FiniteLifecycleOrderStateV1>
      PARSER = new com.google.protobuf.AbstractParser<FiniteLifecycleOrderStateV1>() {
    @java.lang.Override
    public FiniteLifecycleOrderStateV1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FiniteLifecycleOrderStateV1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FiniteLifecycleOrderStateV1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
