// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

@com.google.protobuf.Generated
public interface FiniteLifecycleStateV1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:reef.contracts.calcify.v1.FiniteLifecycleStateV1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string state_version = 1;</code>
   * @return The stateVersion.
   */
  java.lang.String getStateVersion();
  /**
   * <code>string state_version = 1;</code>
   * @return The bytes for stateVersion.
   */
  com.google.protobuf.ByteString
      getStateVersionBytes();

  /**
   * <code>string finite_binding_digest = 2;</code>
   * @return The finiteBindingDigest.
   */
  java.lang.String getFiniteBindingDigest();
  /**
   * <code>string finite_binding_digest = 2;</code>
   * @return The bytes for finiteBindingDigest.
   */
  com.google.protobuf.ByteString
      getFiniteBindingDigestBytes();

  /**
   * <code>string source_profile_hash = 3;</code>
   * @return The sourceProfileHash.
   */
  java.lang.String getSourceProfileHash();
  /**
   * <code>string source_profile_hash = 3;</code>
   * @return The bytes for sourceProfileHash.
   */
  com.google.protobuf.ByteString
      getSourceProfileHashBytes();

  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 orders = 4;</code>
   */
  java.util.List<reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1>
      getOrdersList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 orders = 4;</code>
   */
  reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 getOrders(int index);
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 orders = 4;</code>
   */
  int getOrdersCount();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 orders = 4;</code>
   */
  java.util.List<? extends reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1OrBuilder>
      getOrdersOrBuilderList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1 orders = 4;</code>
   */
  reef.contracts.calcify.v1.FiniteLifecycleOrderStateV1OrBuilder getOrdersOrBuilder(
      int index);

  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 batches = 5;</code>
   */
  java.util.List<reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1>
      getBatchesList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 batches = 5;</code>
   */
  reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 getBatches(int index);
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 batches = 5;</code>
   */
  int getBatchesCount();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 batches = 5;</code>
   */
  java.util.List<? extends reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1OrBuilder>
      getBatchesOrBuilderList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 batches = 5;</code>
   */
  reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1OrBuilder getBatchesOrBuilder(
      int index);

  /**
   * <code>repeated string execution_ids = 6;</code>
   * @return A list containing the executionIds.
   */
  java.util.List<java.lang.String>
      getExecutionIdsList();
  /**
   * <code>repeated string execution_ids = 6;</code>
   * @return The count of executionIds.
   */
  int getExecutionIdsCount();
  /**
   * <code>repeated string execution_ids = 6;</code>
   * @param index The index of the element to return.
   * @return The executionIds at the given index.
   */
  java.lang.String getExecutionIds(int index);
  /**
   * <code>repeated string execution_ids = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the executionIds at the given index.
   */
  com.google.protobuf.ByteString
      getExecutionIdsBytes(int index);

  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 completed_records = 7;</code>
   */
  java.util.List<reef.contracts.calcify.v1.FiniteLifecycleCaptureV1>
      getCompletedRecordsList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 completed_records = 7;</code>
   */
  reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 getCompletedRecords(int index);
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 completed_records = 7;</code>
   */
  int getCompletedRecordsCount();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 completed_records = 7;</code>
   */
  java.util.List<? extends reef.contracts.calcify.v1.FiniteLifecycleCaptureV1OrBuilder>
      getCompletedRecordsOrBuilderList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 completed_records = 7;</code>
   */
  reef.contracts.calcify.v1.FiniteLifecycleCaptureV1OrBuilder getCompletedRecordsOrBuilder(
      int index);

  /**
   * <code>.reef.contracts.calcify.v1.SourceProvenanceV1 completed_frontier = 8;</code>
   * @return Whether the completedFrontier field is set.
   */
  boolean hasCompletedFrontier();
  /**
   * <code>.reef.contracts.calcify.v1.SourceProvenanceV1 completed_frontier = 8;</code>
   * @return The completedFrontier.
   */
  reef.contracts.calcify.v1.SourceProvenanceV1 getCompletedFrontier();
  /**
   * <code>.reef.contracts.calcify.v1.SourceProvenanceV1 completed_frontier = 8;</code>
   */
  reef.contracts.calcify.v1.SourceProvenanceV1OrBuilder getCompletedFrontierOrBuilder();

  /**
   * <code>int64 resume_offset = 9;</code>
   * @return The resumeOffset.
   */
  long getResumeOffset();

  /**
   * <code>uint64 source_bytes = 10;</code>
   * @return The sourceBytes.
   */
  long getSourceBytes();

  /**
   * <code>uint64 capture_bytes = 11;</code>
   * @return The captureBytes.
   */
  long getCaptureBytes();

  /**
   * <code>string fault = 12;</code>
   * @return The fault.
   */
  java.lang.String getFault();
  /**
   * <code>string fault = 12;</code>
   * @return The bytes for fault.
   */
  com.google.protobuf.ByteString
      getFaultBytes();

  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 retained_suffix = 13;</code>
   */
  java.util.List<reef.contracts.calcify.v1.FiniteLifecycleSuffixV1>
      getRetainedSuffixList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 retained_suffix = 13;</code>
   */
  reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 getRetainedSuffix(int index);
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 retained_suffix = 13;</code>
   */
  int getRetainedSuffixCount();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 retained_suffix = 13;</code>
   */
  java.util.List<? extends reef.contracts.calcify.v1.FiniteLifecycleSuffixV1OrBuilder>
      getRetainedSuffixOrBuilderList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 retained_suffix = 13;</code>
   */
  reef.contracts.calcify.v1.FiniteLifecycleSuffixV1OrBuilder getRetainedSuffixOrBuilder(
      int index);

  /**
   * <pre>
   * Exact source/budget/application/genesis identity supplied by registered O2 binding.
   * </pre>
   *
   * <code>bytes binding_identity = 14;</code>
   * @return The bindingIdentity.
   */
  com.google.protobuf.ByteString getBindingIdentity();
}
