// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

/**
 * Protobuf type {@code reef.contracts.calcify.v1.FiniteLifecycleSuffixV1}
 */
@com.google.protobuf.Generated
public final class FiniteLifecycleSuffixV1 extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:reef.contracts.calcify.v1.FiniteLifecycleSuffixV1)
    FiniteLifecycleSuffixV1OrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "FiniteLifecycleSuffixV1");
  }
  // Use FiniteLifecycleSuffixV1.newBuilder() to construct.
  private FiniteLifecycleSuffixV1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FiniteLifecycleSuffixV1() {
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleSuffixV1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleSuffixV1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            reef.contracts.calcify.v1.FiniteLifecycleSuffixV1.class, reef.contracts.calcify.v1.FiniteLifecycleSuffixV1.Builder.class);
  }

  public static final int OFFSET_FIELD_NUMBER = 1;
  private long offset_ = 0L;
  /**
   * <code>int64 offset = 1;</code>
   * @return The offset.
   */
  @java.lang.Override
  public long getOffset() {
    return offset_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes payload = 2;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  public static final int RESUME_OFFSET_FIELD_NUMBER = 3;
  private long resumeOffset_ = 0L;
  /**
   * <code>int64 resume_offset = 3;</code>
   * @return The resumeOffset.
   */
  @java.lang.Override
  public long getResumeOffset() {
    return resumeOffset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (offset_ != 0L) {
      output.writeInt64(1, offset_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(2, payload_);
    }
    if (resumeOffset_ != 0L) {
      output.writeInt64(3, resumeOffset_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (offset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, offset_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, payload_);
    }
    if (resumeOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, resumeOffset_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof reef.contracts.calcify.v1.FiniteLifecycleSuffixV1)) {
      return super.equals(obj);
    }
    reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 other = (reef.contracts.calcify.v1.FiniteLifecycleSuffixV1) obj;

    if (getOffset()
        != other.getOffset()) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (getResumeOffset()
        != other.getResumeOffset()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOffset());
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + RESUME_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getResumeOffset());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reef.contracts.calcify.v1.FiniteLifecycleSuffixV1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reef.contracts.calcify.v1.FiniteLifecycleSuffixV1)
      reef.contracts.calcify.v1.FiniteLifecycleSuffixV1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleSuffixV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleSuffixV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              reef.contracts.calcify.v1.FiniteLifecycleSuffixV1.class, reef.contracts.calcify.v1.FiniteLifecycleSuffixV1.Builder.class);
    }

    // Construct using reef.contracts.calcify.v1.FiniteLifecycleSuffixV1.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      offset_ = 0L;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      resumeOffset_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleSuffixV1_descriptor;
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 getDefaultInstanceForType() {
      return reef.contracts.calcify.v1.FiniteLifecycleSuffixV1.getDefaultInstance();
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 build() {
      reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 buildPartial() {
      reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 result = new reef.contracts.calcify.v1.FiniteLifecycleSuffixV1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.offset_ = offset_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.payload_ = payload_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.resumeOffset_ = resumeOffset_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof reef.contracts.calcify.v1.FiniteLifecycleSuffixV1) {
        return mergeFrom((reef.contracts.calcify.v1.FiniteLifecycleSuffixV1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 other) {
      if (other == reef.contracts.calcify.v1.FiniteLifecycleSuffixV1.getDefaultInstance()) return this;
      if (other.getOffset() != 0L) {
        setOffset(other.getOffset());
      }
      if (!other.getPayload().isEmpty()) {
        setPayload(other.getPayload());
      }
      if (other.getResumeOffset() != 0L) {
        setResumeOffset(other.getResumeOffset());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              offset_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              payload_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              resumeOffset_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long offset_ ;
    /**
     * <code>int64 offset = 1;</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }
    /**
     * <code>int64 offset = 1;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {

      offset_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 offset = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      bitField0_ = (bitField0_ & ~0x00000001);
      offset_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 2;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      payload_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000002);
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    private long resumeOffset_ ;
    /**
     * <code>int64 resume_offset = 3;</code>
     * @return The resumeOffset.
     */
    @java.lang.Override
    public long getResumeOffset() {
      return resumeOffset_;
    }
    /**
     * <code>int64 resume_offset = 3;</code>
     * @param value The resumeOffset to set.
     * @return This builder for chaining.
     */
    public Builder setResumeOffset(long value) {

      resumeOffset_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 resume_offset = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResumeOffset() {
      bitField0_ = (bitField0_ & ~0x00000004);
      resumeOffset_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:reef.contracts.calcify.v1.FiniteLifecycleSuffixV1)
  }

  // @@protoc_insertion_point(class_scope:reef.contracts.calcify.v1.FiniteLifecycleSuffixV1)
  private static final reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new reef.contracts.calcify.v1.FiniteLifecycleSuffixV1();
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FiniteLifecycleSuffixV1>
      PARSER = new com.google.protobuf.AbstractParser<FiniteLifecycleSuffixV1>() {
    @java.lang.Override
    public FiniteLifecycleSuffixV1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FiniteLifecycleSuffixV1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FiniteLifecycleSuffixV1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public reef.contracts.calcify.v1.FiniteLifecycleSuffixV1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
