// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

/**
 * Protobuf type {@code reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1}
 */
@com.google.protobuf.Generated
public final class FiniteLifecycleBatchStateV1 extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1)
    FiniteLifecycleBatchStateV1OrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "FiniteLifecycleBatchStateV1");
  }
  // Use FiniteLifecycleBatchStateV1.newBuilder() to construct.
  private FiniteLifecycleBatchStateV1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FiniteLifecycleBatchStateV1() {
    batchId_ = "";
    batchChecksum_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleBatchStateV1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleBatchStateV1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1.class, reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1.Builder.class);
  }

  private int bitField0_;
  public static final int BATCH_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object batchId_ = "";
  /**
   * <code>string batch_id = 1;</code>
   * @return The batchId.
   */
  @java.lang.Override
  public java.lang.String getBatchId() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batchId_ = s;
      return s;
    }
  }
  /**
   * <code>string batch_id = 1;</code>
   * @return The bytes for batchId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBatchIdBytes() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batchId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BATCH_CHECKSUM_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object batchChecksum_ = "";
  /**
   * <code>string batch_checksum = 2;</code>
   * @return The batchChecksum.
   */
  @java.lang.Override
  public java.lang.String getBatchChecksum() {
    java.lang.Object ref = batchChecksum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batchChecksum_ = s;
      return s;
    }
  }
  /**
   * <code>string batch_checksum = 2;</code>
   * @return The bytes for batchChecksum.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBatchChecksumBytes() {
    java.lang.Object ref = batchChecksum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batchChecksum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRST_CAPTURE_FIELD_NUMBER = 3;
  private reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 firstCapture_;
  /**
   * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
   * @return Whether the firstCapture field is set.
   */
  @java.lang.Override
  public boolean hasFirstCapture() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
   * @return The firstCapture.
   */
  @java.lang.Override
  public reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 getFirstCapture() {
    return firstCapture_ == null ? reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.getDefaultInstance() : firstCapture_;
  }
  /**
   * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
   */
  @java.lang.Override
  public reef.contracts.calcify.v1.FiniteLifecycleCaptureV1OrBuilder getFirstCaptureOrBuilder() {
    return firstCapture_ == null ? reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.getDefaultInstance() : firstCapture_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(batchId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, batchId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(batchChecksum_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, batchChecksum_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getFirstCapture());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(batchId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, batchId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(batchChecksum_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, batchChecksum_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFirstCapture());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1)) {
      return super.equals(obj);
    }
    reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 other = (reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1) obj;

    if (!getBatchId()
        .equals(other.getBatchId())) return false;
    if (!getBatchChecksum()
        .equals(other.getBatchChecksum())) return false;
    if (hasFirstCapture() != other.hasFirstCapture()) return false;
    if (hasFirstCapture()) {
      if (!getFirstCapture()
          .equals(other.getFirstCapture())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBatchId().hashCode();
    hash = (37 * hash) + BATCH_CHECKSUM_FIELD_NUMBER;
    hash = (53 * hash) + getBatchChecksum().hashCode();
    if (hasFirstCapture()) {
      hash = (37 * hash) + FIRST_CAPTURE_FIELD_NUMBER;
      hash = (53 * hash) + getFirstCapture().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1)
      reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleBatchStateV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleBatchStateV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1.class, reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1.Builder.class);
    }

    // Construct using reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetFirstCaptureFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      batchId_ = "";
      batchChecksum_ = "";
      firstCapture_ = null;
      if (firstCaptureBuilder_ != null) {
        firstCaptureBuilder_.dispose();
        firstCaptureBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return reef.contracts.calcify.v1.Calcify.internal_static_reef_contracts_calcify_v1_FiniteLifecycleBatchStateV1_descriptor;
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 getDefaultInstanceForType() {
      return reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1.getDefaultInstance();
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 build() {
      reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 buildPartial() {
      reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 result = new reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.batchId_ = batchId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.batchChecksum_ = batchChecksum_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.firstCapture_ = firstCaptureBuilder_ == null
            ? firstCapture_
            : firstCaptureBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1) {
        return mergeFrom((reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 other) {
      if (other == reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1.getDefaultInstance()) return this;
      if (!other.getBatchId().isEmpty()) {
        batchId_ = other.batchId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBatchChecksum().isEmpty()) {
        batchChecksum_ = other.batchChecksum_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasFirstCapture()) {
        mergeFirstCapture(other.getFirstCapture());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              batchId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              batchChecksum_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetFirstCaptureFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object batchId_ = "";
    /**
     * <code>string batch_id = 1;</code>
     * @return The batchId.
     */
    public java.lang.String getBatchId() {
      java.lang.Object ref = batchId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string batch_id = 1;</code>
     * @return The bytes for batchId.
     */
    public com.google.protobuf.ByteString
        getBatchIdBytes() {
      java.lang.Object ref = batchId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string batch_id = 1;</code>
     * @param value The batchId to set.
     * @return This builder for chaining.
     */
    public Builder setBatchId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      batchId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string batch_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchId() {
      batchId_ = getDefaultInstance().getBatchId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string batch_id = 1;</code>
     * @param value The bytes for batchId to set.
     * @return This builder for chaining.
     */
    public Builder setBatchIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      batchId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object batchChecksum_ = "";
    /**
     * <code>string batch_checksum = 2;</code>
     * @return The batchChecksum.
     */
    public java.lang.String getBatchChecksum() {
      java.lang.Object ref = batchChecksum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchChecksum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string batch_checksum = 2;</code>
     * @return The bytes for batchChecksum.
     */
    public com.google.protobuf.ByteString
        getBatchChecksumBytes() {
      java.lang.Object ref = batchChecksum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchChecksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string batch_checksum = 2;</code>
     * @param value The batchChecksum to set.
     * @return This builder for chaining.
     */
    public Builder setBatchChecksum(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      batchChecksum_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string batch_checksum = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchChecksum() {
      batchChecksum_ = getDefaultInstance().getBatchChecksum();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string batch_checksum = 2;</code>
     * @param value The bytes for batchChecksum to set.
     * @return This builder for chaining.
     */
    public Builder setBatchChecksumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      batchChecksum_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 firstCapture_;
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.calcify.v1.FiniteLifecycleCaptureV1, reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.Builder, reef.contracts.calcify.v1.FiniteLifecycleCaptureV1OrBuilder> firstCaptureBuilder_;
    /**
     * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
     * @return Whether the firstCapture field is set.
     */
    public boolean hasFirstCapture() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
     * @return The firstCapture.
     */
    public reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 getFirstCapture() {
      if (firstCaptureBuilder_ == null) {
        return firstCapture_ == null ? reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.getDefaultInstance() : firstCapture_;
      } else {
        return firstCaptureBuilder_.getMessage();
      }
    }
    /**
     * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
     */
    public Builder setFirstCapture(reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 value) {
      if (firstCaptureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        firstCapture_ = value;
      } else {
        firstCaptureBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
     */
    public Builder setFirstCapture(
        reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.Builder builderForValue) {
      if (firstCaptureBuilder_ == null) {
        firstCapture_ = builderForValue.build();
      } else {
        firstCaptureBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
     */
    public Builder mergeFirstCapture(reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 value) {
      if (firstCaptureBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          firstCapture_ != null &&
          firstCapture_ != reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.getDefaultInstance()) {
          getFirstCaptureBuilder().mergeFrom(value);
        } else {
          firstCapture_ = value;
        }
      } else {
        firstCaptureBuilder_.mergeFrom(value);
      }
      if (firstCapture_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
     */
    public Builder clearFirstCapture() {
      bitField0_ = (bitField0_ & ~0x00000004);
      firstCapture_ = null;
      if (firstCaptureBuilder_ != null) {
        firstCaptureBuilder_.dispose();
        firstCaptureBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
     */
    public reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.Builder getFirstCaptureBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetFirstCaptureFieldBuilder().getBuilder();
    }
    /**
     * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
     */
    public reef.contracts.calcify.v1.FiniteLifecycleCaptureV1OrBuilder getFirstCaptureOrBuilder() {
      if (firstCaptureBuilder_ != null) {
        return firstCaptureBuilder_.getMessageOrBuilder();
      } else {
        return firstCapture_ == null ?
            reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.getDefaultInstance() : firstCapture_;
      }
    }
    /**
     * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        reef.contracts.calcify.v1.FiniteLifecycleCaptureV1, reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.Builder, reef.contracts.calcify.v1.FiniteLifecycleCaptureV1OrBuilder>
        internalGetFirstCaptureFieldBuilder() {
      if (firstCaptureBuilder_ == null) {
        firstCaptureBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            reef.contracts.calcify.v1.FiniteLifecycleCaptureV1, reef.contracts.calcify.v1.FiniteLifecycleCaptureV1.Builder, reef.contracts.calcify.v1.FiniteLifecycleCaptureV1OrBuilder>(
                getFirstCapture(),
                getParentForChildren(),
                isClean());
        firstCapture_ = null;
      }
      return firstCaptureBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1)
  }

  // @@protoc_insertion_point(class_scope:reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1)
  private static final reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1();
  }

  public static reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FiniteLifecycleBatchStateV1>
      PARSER = new com.google.protobuf.AbstractParser<FiniteLifecycleBatchStateV1>() {
    @java.lang.Override
    public FiniteLifecycleBatchStateV1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FiniteLifecycleBatchStateV1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FiniteLifecycleBatchStateV1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
