// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

@com.google.protobuf.Generated
public interface FiniteLifecycleBatchStateV1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:reef.contracts.calcify.v1.FiniteLifecycleBatchStateV1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string batch_id = 1;</code>
   * @return The batchId.
   */
  java.lang.String getBatchId();
  /**
   * <code>string batch_id = 1;</code>
   * @return The bytes for batchId.
   */
  com.google.protobuf.ByteString
      getBatchIdBytes();

  /**
   * <code>string batch_checksum = 2;</code>
   * @return The batchChecksum.
   */
  java.lang.String getBatchChecksum();
  /**
   * <code>string batch_checksum = 2;</code>
   * @return The bytes for batchChecksum.
   */
  com.google.protobuf.ByteString
      getBatchChecksumBytes();

  /**
   * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
   * @return Whether the firstCapture field is set.
   */
  boolean hasFirstCapture();
  /**
   * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
   * @return The firstCapture.
   */
  reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 getFirstCapture();
  /**
   * <code>.reef.contracts.calcify.v1.FiniteLifecycleCaptureV1 first_capture = 3;</code>
   */
  reef.contracts.calcify.v1.FiniteLifecycleCaptureV1OrBuilder getFirstCaptureOrBuilder();
}
