// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

@com.google.protobuf.Generated
public interface LifecycleRevisionIdV1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:reef.contracts.calcify.v1.LifecycleRevisionIdV1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 command = 1;</code>
   * @return Whether the command field is set.
   */
  boolean hasCommand();
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 command = 1;</code>
   * @return The command.
   */
  reef.contracts.calcify.v1.LifecycleMemberIdV1 getCommand();
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 command = 1;</code>
   */
  reef.contracts.calcify.v1.LifecycleMemberIdV1OrBuilder getCommandOrBuilder();

  /**
   * <code>uint32 revision = 2;</code>
   * @return The revision.
   */
  int getRevision();
}
