// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

@com.google.protobuf.Generated
public interface LifecycleMemberV1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:reef.contracts.calcify.v1.LifecycleMemberV1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 id = 1;</code>
   * @return The id.
   */
  reef.contracts.calcify.v1.LifecycleMemberIdV1 getId();
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 id = 1;</code>
   */
  reef.contracts.calcify.v1.LifecycleMemberIdV1OrBuilder getIdOrBuilder();

  /**
   * <code>.reef.contracts.calcify.v1.LifecycleDispositionV1 disposition = 2;</code>
   * @return The enum numeric value on the wire for disposition.
   */
  int getDispositionValue();
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleDispositionV1 disposition = 2;</code>
   * @return The disposition.
   */
  reef.contracts.calcify.v1.LifecycleDispositionV1 getDisposition();

  /**
   * <code>.reef.contracts.calcify.v1.OrderLifecycleCommandV1 command = 3;</code>
   * @return Whether the command field is set.
   */
  boolean hasCommand();
  /**
   * <code>.reef.contracts.calcify.v1.OrderLifecycleCommandV1 command = 3;</code>
   * @return The command.
   */
  reef.contracts.calcify.v1.OrderLifecycleCommandV1 getCommand();
  /**
   * <code>.reef.contracts.calcify.v1.OrderLifecycleCommandV1 command = 3;</code>
   */
  reef.contracts.calcify.v1.OrderLifecycleCommandV1OrBuilder getCommandOrBuilder();

  /**
   * <code>string command_payload_hash = 4;</code>
   * @return The commandPayloadHash.
   */
  java.lang.String getCommandPayloadHash();
  /**
   * <code>string command_payload_hash = 4;</code>
   * @return The bytes for commandPayloadHash.
   */
  com.google.protobuf.ByteString
      getCommandPayloadHashBytes();

  /**
   * <code>string outcome_status = 5;</code>
   * @return The outcomeStatus.
   */
  java.lang.String getOutcomeStatus();
  /**
   * <code>string outcome_status = 5;</code>
   * @return The bytes for outcomeStatus.
   */
  com.google.protobuf.ByteString
      getOutcomeStatusBytes();

  /**
   * <code>.reef.contracts.orderexecution.v1.OrderAccepted accepted = 6;</code>
   * @return Whether the accepted field is set.
   */
  boolean hasAccepted();
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderAccepted accepted = 6;</code>
   * @return The accepted.
   */
  reef.contracts.orderexecution.v1.OrderAccepted getAccepted();
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderAccepted accepted = 6;</code>
   */
  reef.contracts.orderexecution.v1.OrderAcceptedOrBuilder getAcceptedOrBuilder();

  /**
   * <code>.reef.contracts.orderexecution.v1.OrderRejected rejected = 7;</code>
   * @return Whether the rejected field is set.
   */
  boolean hasRejected();
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderRejected rejected = 7;</code>
   * @return The rejected.
   */
  reef.contracts.orderexecution.v1.OrderRejected getRejected();
  /**
   * <code>.reef.contracts.orderexecution.v1.OrderRejected rejected = 7;</code>
   */
  reef.contracts.orderexecution.v1.OrderRejectedOrBuilder getRejectedOrBuilder();

  /**
   * <code>.reef.contracts.calcify.v1.TradeSourceV1 trade = 8;</code>
   * @return Whether the trade field is set.
   */
  boolean hasTrade();
  /**
   * <code>.reef.contracts.calcify.v1.TradeSourceV1 trade = 8;</code>
   * @return The trade.
   */
  reef.contracts.calcify.v1.TradeSourceV1 getTrade();
  /**
   * <code>.reef.contracts.calcify.v1.TradeSourceV1 trade = 8;</code>
   */
  reef.contracts.calcify.v1.TradeSourceV1OrBuilder getTradeOrBuilder();

  /**
   * <code>repeated .reef.contracts.calcify.v1.LifecycleDependencyV1 dependencies = 9;</code>
   */
  java.util.List<reef.contracts.calcify.v1.LifecycleDependencyV1>
      getDependenciesList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.LifecycleDependencyV1 dependencies = 9;</code>
   */
  reef.contracts.calcify.v1.LifecycleDependencyV1 getDependencies(int index);
  /**
   * <code>repeated .reef.contracts.calcify.v1.LifecycleDependencyV1 dependencies = 9;</code>
   */
  int getDependenciesCount();
  /**
   * <code>repeated .reef.contracts.calcify.v1.LifecycleDependencyV1 dependencies = 9;</code>
   */
  java.util.List<? extends reef.contracts.calcify.v1.LifecycleDependencyV1OrBuilder>
      getDependenciesOrBuilderList();
  /**
   * <code>repeated .reef.contracts.calcify.v1.LifecycleDependencyV1 dependencies = 9;</code>
   */
  reef.contracts.calcify.v1.LifecycleDependencyV1OrBuilder getDependenciesOrBuilder(
      int index);

  /**
   * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 resulting_revision = 10;</code>
   * @return Whether the resultingRevision field is set.
   */
  boolean hasResultingRevision();
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 resulting_revision = 10;</code>
   * @return The resultingRevision.
   */
  reef.contracts.calcify.v1.LifecycleRevisionIdV1 getResultingRevision();
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleRevisionIdV1 resulting_revision = 10;</code>
   */
  reef.contracts.calcify.v1.LifecycleRevisionIdV1OrBuilder getResultingRevisionOrBuilder();

  /**
   * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 immutable_acceptance = 11;</code>
   * @return Whether the immutableAcceptance field is set.
   */
  boolean hasImmutableAcceptance();
  /**
   * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 immutable_acceptance = 11;</code>
   * @return The immutableAcceptance.
   */
  reef.contracts.calcify.v1.AcceptedOrderSourceV1 getImmutableAcceptance();
  /**
   * <code>.reef.contracts.calcify.v1.AcceptedOrderSourceV1 immutable_acceptance = 11;</code>
   */
  reef.contracts.calcify.v1.AcceptedOrderSourceV1OrBuilder getImmutableAcceptanceOrBuilder();

  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 replay_of = 12;</code>
   * @return Whether the replayOf field is set.
   */
  boolean hasReplayOf();
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 replay_of = 12;</code>
   * @return The replayOf.
   */
  reef.contracts.calcify.v1.LifecycleMemberIdV1 getReplayOf();
  /**
   * <code>.reef.contracts.calcify.v1.LifecycleMemberIdV1 replay_of = 12;</code>
   */
  reef.contracts.calcify.v1.LifecycleMemberIdV1OrBuilder getReplayOfOrBuilder();

  /**
   * <pre>
   * Exact buy/sell execution facts retain canonical maker/taker attribution.
   * </pre>
   *
   * <code>repeated .reef.contracts.orderexecution.v1.ExecutionCreated executions = 13;</code>
   */
  java.util.List<reef.contracts.orderexecution.v1.ExecutionCreated>
      getExecutionsList();
  /**
   * <pre>
   * Exact buy/sell execution facts retain canonical maker/taker attribution.
   * </pre>
   *
   * <code>repeated .reef.contracts.orderexecution.v1.ExecutionCreated executions = 13;</code>
   */
  reef.contracts.orderexecution.v1.ExecutionCreated getExecutions(int index);
  /**
   * <pre>
   * Exact buy/sell execution facts retain canonical maker/taker attribution.
   * </pre>
   *
   * <code>repeated .reef.contracts.orderexecution.v1.ExecutionCreated executions = 13;</code>
   */
  int getExecutionsCount();
  /**
   * <pre>
   * Exact buy/sell execution facts retain canonical maker/taker attribution.
   * </pre>
   *
   * <code>repeated .reef.contracts.orderexecution.v1.ExecutionCreated executions = 13;</code>
   */
  java.util.List<? extends reef.contracts.orderexecution.v1.ExecutionCreatedOrBuilder>
      getExecutionsOrBuilderList();
  /**
   * <pre>
   * Exact buy/sell execution facts retain canonical maker/taker attribution.
   * </pre>
   *
   * <code>repeated .reef.contracts.orderexecution.v1.ExecutionCreated executions = 13;</code>
   */
  reef.contracts.orderexecution.v1.ExecutionCreatedOrBuilder getExecutionsOrBuilder(
      int index);
}
