// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

/**
 * <pre>
 * Additive finite capture contract. Existing Phase 1 links remain unchanged.
 * </pre>
 *
 * Protobuf enum {@code reef.contracts.calcify.v1.LifecycleCommandKindV1}
 */
@com.google.protobuf.Generated
public enum LifecycleCommandKindV1
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LIFECYCLE_COMMAND_UNSPECIFIED = 0;</code>
   */
  LIFECYCLE_COMMAND_UNSPECIFIED(0),
  /**
   * <code>LIFECYCLE_COMMAND_SUBMIT = 1;</code>
   */
  LIFECYCLE_COMMAND_SUBMIT(1),
  /**
   * <code>LIFECYCLE_COMMAND_MODIFY = 2;</code>
   */
  LIFECYCLE_COMMAND_MODIFY(2),
  /**
   * <code>LIFECYCLE_COMMAND_CANCEL = 3;</code>
   */
  LIFECYCLE_COMMAND_CANCEL(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "LifecycleCommandKindV1");
  }
  /**
   * <code>LIFECYCLE_COMMAND_UNSPECIFIED = 0;</code>
   */
  public static final int LIFECYCLE_COMMAND_UNSPECIFIED_VALUE = 0;
  /**
   * <code>LIFECYCLE_COMMAND_SUBMIT = 1;</code>
   */
  public static final int LIFECYCLE_COMMAND_SUBMIT_VALUE = 1;
  /**
   * <code>LIFECYCLE_COMMAND_MODIFY = 2;</code>
   */
  public static final int LIFECYCLE_COMMAND_MODIFY_VALUE = 2;
  /**
   * <code>LIFECYCLE_COMMAND_CANCEL = 3;</code>
   */
  public static final int LIFECYCLE_COMMAND_CANCEL_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LifecycleCommandKindV1 valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LifecycleCommandKindV1 forNumber(int value) {
    switch (value) {
      case 0: return LIFECYCLE_COMMAND_UNSPECIFIED;
      case 1: return LIFECYCLE_COMMAND_SUBMIT;
      case 2: return LIFECYCLE_COMMAND_MODIFY;
      case 3: return LIFECYCLE_COMMAND_CANCEL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LifecycleCommandKindV1>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LifecycleCommandKindV1> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LifecycleCommandKindV1>() {
          public LifecycleCommandKindV1 findValueByNumber(int number) {
            return LifecycleCommandKindV1.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return reef.contracts.calcify.v1.Calcify.getDescriptor().getEnumTypes().get(0);
  }

  private static final LifecycleCommandKindV1[] VALUES = values();

  public static LifecycleCommandKindV1 valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LifecycleCommandKindV1(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:reef.contracts.calcify.v1.LifecycleCommandKindV1)
}
