// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contracts/proto/calcify.proto
// Protobuf Java Version: 4.33.2

package reef.contracts.calcify.v1;

@com.google.protobuf.Generated
public interface LifecycleModifyV1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:reef.contracts.calcify.v1.LifecycleModifyV1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string quantity_units = 1;</code>
   * @return The quantityUnits.
   */
  java.lang.String getQuantityUnits();
  /**
   * <code>string quantity_units = 1;</code>
   * @return The bytes for quantityUnits.
   */
  com.google.protobuf.ByteString
      getQuantityUnitsBytes();

  /**
   * <code>string limit_price = 2;</code>
   * @return The limitPrice.
   */
  java.lang.String getLimitPrice();
  /**
   * <code>string limit_price = 2;</code>
   * @return The bytes for limitPrice.
   */
  com.google.protobuf.ByteString
      getLimitPriceBytes();
}
